/*
 * Disk.c - disk access layer
 *
 *  This code implements low-level disk access for PVR utilities
 *
 *  This code was developed by tibor/LaSat and ported to Linux by metterschling
 *
 * This file is part of pc2box, a free C++ PVR file retrieval utility
 *
 *
 * This program is free software; you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */
#if !defined(_WIN32) && !defined(_WIN64)
// The most important line: enable large file (>4GB) support
#define _FILE_OFFSET_BITS 64
#define _LARGEFILE64_SOURCE
#endif

#include "vfs.h"

#if !defined(_WIN32) && !defined(_WIN64)
#include <errno.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <assert.h>
#include <unistd.h>
#endif

#if defined(_WIN32) || defined(_WIN64)
PUCHAR
VfsStatusToString ( IN NTSTATUS Status )
{
    switch (Status)
    {
    case 0x00000000: return (PUCHAR)"STATUS_SUCCESS";
    case 0x00000001: return (PUCHAR)"STATUS_WAIT_1";
    case 0x00000002: return (PUCHAR)"STATUS_WAIT_2";
    case 0x00000003: return (PUCHAR)"STATUS_WAIT_3";
    case 0x0000003F: return (PUCHAR)"STATUS_WAIT_63";
    case 0x00000080: return (PUCHAR)"STATUS_ABANDONED_WAIT_0";
    case 0x000000BF: return (PUCHAR)"STATUS_ABANDONED_WAIT_63";
    case 0x000000C0: return (PUCHAR)"STATUS_USER_APC";
    case 0x00000100: return (PUCHAR)"STATUS_KERNEL_APC";
    case 0x00000101: return (PUCHAR)"STATUS_ALERTED";
    case 0x00000102: return (PUCHAR)"STATUS_TIMEOUT";
    case 0x00000103: return (PUCHAR)"STATUS_PENDING";
    case 0x00000104: return (PUCHAR)"STATUS_REPARSE";
    case 0x00000105: return (PUCHAR)"STATUS_MORE_ENTRIES";
    case 0x00000106: return (PUCHAR)"STATUS_NOT_ALL_ASSIGNED";
    case 0x00000107: return (PUCHAR)"STATUS_SOME_NOT_MAPPED";
    case 0x00000108: return (PUCHAR)"STATUS_OPLOCK_BREAK_IN_PROGRESS";
    case 0x00000109: return (PUCHAR)"STATUS_VOLUME_MOUNTED";
    case 0x0000010A: return (PUCHAR)"STATUS_RXACT_COMMITTED";
    case 0x0000010B: return (PUCHAR)"STATUS_NOTIFY_CLEANUP";
    case 0x0000010C: return (PUCHAR)"STATUS_NOTIFY_ENUM_DIR";
    case 0x0000010D: return (PUCHAR)"STATUS_NO_QUOTAS_FOR_ACCOUNT";
    case 0x0000010E: return (PUCHAR)"STATUS_PRIMARY_TRANSPORT_CONNECT_FAILED";
    case 0x00000110: return (PUCHAR)"STATUS_PAGE_FAULT_TRANSITION";
    case 0x00000111: return (PUCHAR)"STATUS_PAGE_FAULT_DEMAND_ZERO";
    case 0x00000112: return (PUCHAR)"STATUS_PAGE_FAULT_COPY_ON_WRITE";
    case 0x00000113: return (PUCHAR)"STATUS_PAGE_FAULT_GUARD_PAGE";
    case 0x00000114: return (PUCHAR)"STATUS_PAGE_FAULT_PAGING_FILE";
    case 0x00000115: return (PUCHAR)"STATUS_CACHE_PAGE_LOCKED";
    case 0x00000116: return (PUCHAR)"STATUS_CRASH_DUMP";
    case 0x00000117: return (PUCHAR)"STATUS_BUFFER_ALL_ZEROS";
    case 0x00000118: return (PUCHAR)"STATUS_REPARSE_OBJECT";
    case 0x00000119: return (PUCHAR)"STATUS_RESOURCE_REQUIREMENTS_CHANGED";
    case 0x00000120: return (PUCHAR)"STATUS_TRANSLATION_COMPLETE";
    case 0x00000121: return (PUCHAR)"STATUS_DS_MEMBERSHIP_EVALUATED_LOCALLY";
    case 0x00010001: return (PUCHAR)"DBG_EXCEPTION_HANDLED";
    case 0x00010002: return (PUCHAR)"DBG_CONTINUE";
    case 0x40000000: return (PUCHAR)"STATUS_OBJECT_NAME_EXISTS";
    case 0x40000001: return (PUCHAR)"STATUS_THREAD_WAS_SUSPENDED";
    case 0x40000002: return (PUCHAR)"STATUS_WORKING_SET_LIMIT_RANGE";
    case 0x40000003: return (PUCHAR)"STATUS_IMAGE_NOT_AT_BASE";
    case 0x40000004: return (PUCHAR)"STATUS_RXACT_STATE_CREATED";
    case 0x40000005: return (PUCHAR)"STATUS_SEGMENT_NOTIFICATION";
    case 0x40000006: return (PUCHAR)"STATUS_LOCAL_USER_SESSION_KEY";
    case 0x40000007: return (PUCHAR)"STATUS_BAD_CURRENT_DIRECTORY";
    case 0x40000008: return (PUCHAR)"STATUS_SERIAL_MORE_WRITES";
    case 0x40000009: return (PUCHAR)"STATUS_REGISTRY_RECOVERED";
    case 0x4000000A: return (PUCHAR)"STATUS_FT_READ_RECOVERY_FROM_BACKUP";
    case 0x4000000B: return (PUCHAR)"STATUS_FT_WRITE_RECOVERY";
    case 0x4000000C: return (PUCHAR)"STATUS_SERIAL_COUNTER_TIMEOUT";
    case 0x4000000D: return (PUCHAR)"STATUS_NULL_LM_PASSWORD";
    case 0x4000000E: return (PUCHAR)"STATUS_IMAGE_MACHINE_TYPE_MISMATCH";
    case 0x4000000F: return (PUCHAR)"STATUS_RECEIVE_PARTIAL";
    case 0x40000010: return (PUCHAR)"STATUS_RECEIVE_EXPEDITED";
    case 0x40000011: return (PUCHAR)"STATUS_RECEIVE_PARTIAL_EXPEDITED";
    case 0x40000012: return (PUCHAR)"STATUS_EVENT_DONE";
    case 0x40000013: return (PUCHAR)"STATUS_EVENT_PENDING";
    case 0x40000014: return (PUCHAR)"STATUS_CHECKING_FILE_SYSTEM";
    case 0x40000015: return (PUCHAR)"STATUS_FATAL_APP_EXIT";
    case 0x40000016: return (PUCHAR)"STATUS_PREDEFINED_HANDLE";
    case 0x40000017: return (PUCHAR)"STATUS_WAS_UNLOCKED";
    case 0x40000018: return (PUCHAR)"STATUS_SERVICE_NOTIFICATION";
    case 0x40000019: return (PUCHAR)"STATUS_WAS_LOCKED";
    case 0x4000001A: return (PUCHAR)"STATUS_LOG_HARD_ERROR";
    case 0x4000001B: return (PUCHAR)"STATUS_ALREADY_WIN32";
    case 0x4000001C: return (PUCHAR)"STATUS_WX86_UNSIMULATE";
    case 0x4000001D: return (PUCHAR)"STATUS_WX86_CONTINUE";
    case 0x4000001E: return (PUCHAR)"STATUS_WX86_SINGLE_STEP";
    case 0x4000001F: return (PUCHAR)"STATUS_WX86_BREAKPOINT";
    case 0x40000020: return (PUCHAR)"STATUS_WX86_EXCEPTION_CONTINUE";
    case 0x40000021: return (PUCHAR)"STATUS_WX86_EXCEPTION_LASTCHANCE";
    case 0x40000022: return (PUCHAR)"STATUS_WX86_EXCEPTION_CHAIN";
    case 0x40000023: return (PUCHAR)"STATUS_IMAGE_MACHINE_TYPE_MISMATCH_EXE";
    case 0x40000024: return (PUCHAR)"STATUS_NO_YIELD_PERFORMED";
    case 0x40000025: return (PUCHAR)"STATUS_TIMER_RESUME_IGNORED";
    case 0x40000026: return (PUCHAR)"STATUS_ARBITRATION_UNHANDLED";
    case 0x40000027: return (PUCHAR)"STATUS_CARDBUS_NOT_SUPPORTED";
    case 0x40000028: return (PUCHAR)"STATUS_WX86_CREATEWX86TIB";
    case 0x40000029: return (PUCHAR)"STATUS_MP_PROCESSOR_MISMATCH";
    case 0x40010001: return (PUCHAR)"DBG_REPLY_LATER";
    case 0x40010002: return (PUCHAR)"DBG_UNABLE_TO_PROVIDE_HANDLE";
    case 0x40010003: return (PUCHAR)"DBG_TERMINATE_THREAD";
    case 0x40010004: return (PUCHAR)"DBG_TERMINATE_PROCESS";
    case 0x40010005: return (PUCHAR)"DBG_CONTROL_C";
    case 0x40010006: return (PUCHAR)"DBG_PRINTEXCEPTION_C";
    case 0x40010007: return (PUCHAR)"DBG_RIPEXCEPTION";
    case 0x40010008: return (PUCHAR)"DBG_CONTROL_BREAK";
    case 0x80000001: return (PUCHAR)"STATUS_GUARD_PAGE_VIOLATION";
    case 0x80000002: return (PUCHAR)"STATUS_DATATYPE_MISALIGNMENT";
    case 0x80000003: return (PUCHAR)"STATUS_BREAKPOINT";
    case 0x80000004: return (PUCHAR)"STATUS_SINGLE_STEP";
    case 0x80000005: return (PUCHAR)"STATUS_BUFFER_OVERFLOW";
    case 0x80000006: return (PUCHAR)"STATUS_NO_MORE_FILES";
    case 0x80000007: return (PUCHAR)"STATUS_WAKE_SYSTEM_DEBUGGER";
    case 0x8000000A: return (PUCHAR)"STATUS_HANDLES_CLOSED";
    case 0x8000000B: return (PUCHAR)"STATUS_NO_INHERITANCE";
    case 0x8000000C: return (PUCHAR)"STATUS_GUID_SUBSTITUTION_MADE";
    case 0x8000000D: return (PUCHAR)"STATUS_PARTIAL_COPY";
    case 0x8000000E: return (PUCHAR)"STATUS_DEVICE_PAPER_EMPTY";
    case 0x8000000F: return (PUCHAR)"STATUS_DEVICE_POWERED_OFF";
    case 0x80000010: return (PUCHAR)"STATUS_DEVICE_OFF_LINE";
    case 0x80000011: return (PUCHAR)"STATUS_DEVICE_BUSY";
    case 0x80000012: return (PUCHAR)"STATUS_NO_MORE_EAS";
    case 0x80000013: return (PUCHAR)"STATUS_INVALID_EA_NAME";
    case 0x80000014: return (PUCHAR)"STATUS_EA_LIST_INCONSISTENT";
    case 0x80000015: return (PUCHAR)"STATUS_INVALID_EA_FLAG";
    case 0x80000016: return (PUCHAR)"STATUS_VERIFY_REQUIRED";
    case 0x80000017: return (PUCHAR)"STATUS_EXTRANEOUS_INFORMATION";
    case 0x80000018: return (PUCHAR)"STATUS_RXACT_COMMIT_NECESSARY";
    case 0x8000001A: return (PUCHAR)"STATUS_NO_MORE_ENTRIES";
    case 0x8000001B: return (PUCHAR)"STATUS_FILEMARK_DETECTED";
    case 0x8000001C: return (PUCHAR)"STATUS_MEDIA_CHANGED";
    case 0x8000001D: return (PUCHAR)"STATUS_BUS_RESET";
    case 0x8000001E: return (PUCHAR)"STATUS_END_OF_MEDIA";
    case 0x8000001F: return (PUCHAR)"STATUS_BEGINNING_OF_MEDIA";
    case 0x80000020: return (PUCHAR)"STATUS_MEDIA_CHECK";
    case 0x80000021: return (PUCHAR)"STATUS_SETMARK_DETECTED";
    case 0x80000022: return (PUCHAR)"STATUS_NO_DATA_DETECTED";
    case 0x80000023: return (PUCHAR)"STATUS_REDIRECTOR_HAS_OPEN_HANDLES";
    case 0x80000024: return (PUCHAR)"STATUS_SERVER_HAS_OPEN_HANDLES";
    case 0x80000025: return (PUCHAR)"STATUS_ALREADY_DISCONNECTED";
    case 0x80000026: return (PUCHAR)"STATUS_LONGJUMP";
    case 0x80010001: return (PUCHAR)"DBG_EXCEPTION_NOT_HANDLED";
    case 0xC0000001: return (PUCHAR)"STATUS_UNSUCCESSFUL";
    case 0xC0000002: return (PUCHAR)"STATUS_NOT_IMPLEMENTED";
    case 0xC0000003: return (PUCHAR)"STATUS_INVALID_INFO_CLASS";
    case 0xC0000004: return (PUCHAR)"STATUS_INFO_LENGTH_MISMATCH";
    case 0xC0000005: return (PUCHAR)"STATUS_ACCESS_VIOLATION";
    case 0xC0000006: return (PUCHAR)"STATUS_IN_PAGE_ERROR";
    case 0xC0000007: return (PUCHAR)"STATUS_PAGEFILE_QUOTA";
    case 0xC0000008: return (PUCHAR)"STATUS_INVALID_HANDLE";
    case 0xC0000009: return (PUCHAR)"STATUS_BAD_INITIAL_STACK";
    case 0xC000000A: return (PUCHAR)"STATUS_BAD_INITIAL_PC";
    case 0xC000000B: return (PUCHAR)"STATUS_INVALID_CID";
    case 0xC000000C: return (PUCHAR)"STATUS_TIMER_NOT_CANCELED";
    case 0xC000000D: return (PUCHAR)"STATUS_INVALID_PARAMETER";
    case 0xC000000E: return (PUCHAR)"STATUS_NO_SUCH_DEVICE";
    case 0xC000000F: return (PUCHAR)"STATUS_NO_SUCH_FILE";
    case 0xC0000010: return (PUCHAR)"STATUS_INVALID_DEVICE_REQUEST";
    case 0xC0000011: return (PUCHAR)"STATUS_END_OF_FILE";
    case 0xC0000012: return (PUCHAR)"STATUS_WRONG_VOLUME";
    case 0xC0000013: return (PUCHAR)"STATUS_NO_MEDIA_IN_DEVICE";
    case 0xC0000014: return (PUCHAR)"STATUS_UNRECOGNIZED_MEDIA";
    case 0xC0000015: return (PUCHAR)"STATUS_NONEXISTENT_SECTOR";
    case 0xC0000016: return (PUCHAR)"STATUS_MORE_PROCESSING_REQUIRED";
    case 0xC0000017: return (PUCHAR)"STATUS_NO_MEMORY";
    case 0xC0000018: return (PUCHAR)"STATUS_CONFLICTING_ADDRESSES";
    case 0xC0000019: return (PUCHAR)"STATUS_NOT_MAPPED_VIEW";
    case 0xC000001A: return (PUCHAR)"STATUS_UNABLE_TO_FREE_VM";
    case 0xC000001B: return (PUCHAR)"STATUS_UNABLE_TO_DELETE_SECTION";
    case 0xC000001C: return (PUCHAR)"STATUS_INVALID_SYSTEM_SERVICE";
    case 0xC000001D: return (PUCHAR)"STATUS_ILLEGAL_INSTRUCTION";
    case 0xC000001E: return (PUCHAR)"STATUS_INVALID_LOCK_SEQUENCE";
    case 0xC000001F: return (PUCHAR)"STATUS_INVALID_VIEW_SIZE";
    case 0xC0000020: return (PUCHAR)"STATUS_INVALID_FILE_FOR_SECTION";
    case 0xC0000021: return (PUCHAR)"STATUS_ALREADY_COMMITTED";
    case 0xC0000022: return (PUCHAR)"STATUS_ACCESS_DENIED";
    case 0xC0000023: return (PUCHAR)"STATUS_BUFFER_TOO_SMALL";
    case 0xC0000024: return (PUCHAR)"STATUS_OBJECT_TYPE_MISMATCH";
    case 0xC0000025: return (PUCHAR)"STATUS_NONCONTINUABLE_EXCEPTION";
    case 0xC0000026: return (PUCHAR)"STATUS_INVALID_DISPOSITION";
    case 0xC0000027: return (PUCHAR)"STATUS_UNWIND";
    case 0xC0000028: return (PUCHAR)"STATUS_BAD_STACK";
    case 0xC0000029: return (PUCHAR)"STATUS_INVALID_UNWIND_TARGET";
    case 0xC000002A: return (PUCHAR)"STATUS_NOT_LOCKED";
    case 0xC000002B: return (PUCHAR)"STATUS_PARITY_ERROR";
    case 0xC000002C: return (PUCHAR)"STATUS_UNABLE_TO_DECOMMIT_VM";
    case 0xC000002D: return (PUCHAR)"STATUS_NOT_COMMITTED";
    case 0xC000002E: return (PUCHAR)"STATUS_INVALID_PORT_ATTRIBUTES";
    case 0xC000002F: return (PUCHAR)"STATUS_PORT_MESSAGE_TOO_LONG";
    case 0xC0000030: return (PUCHAR)"STATUS_INVALID_PARAMETER_MIX";
    case 0xC0000031: return (PUCHAR)"STATUS_INVALID_QUOTA_LOWER";
    case 0xC0000032: return (PUCHAR)"STATUS_DISK_CORRUPT_ERROR";
    case 0xC0000033: return (PUCHAR)"STATUS_OBJECT_NAME_INVALID";
    case 0xC0000034: return (PUCHAR)"STATUS_OBJECT_NAME_NOT_FOUND";
    case 0xC0000035: return (PUCHAR)"STATUS_OBJECT_NAME_COLLISION";
    case 0xC0000037: return (PUCHAR)"STATUS_PORT_DISCONNECTED";
    case 0xC0000038: return (PUCHAR)"STATUS_DEVICE_ALREADY_ATTACHED";
    case 0xC0000039: return (PUCHAR)"STATUS_OBJECT_PATH_INVALID";
    case 0xC000003A: return (PUCHAR)"STATUS_OBJECT_PATH_NOT_FOUND";
    case 0xC000003B: return (PUCHAR)"STATUS_OBJECT_PATH_SYNTAX_BAD";
    case 0xC000003C: return (PUCHAR)"STATUS_DATA_OVERRUN";
    case 0xC000003D: return (PUCHAR)"STATUS_DATA_LATE_ERROR";
    case 0xC000003E: return (PUCHAR)"STATUS_DATA_ERROR";
    case 0xC000003F: return (PUCHAR)"STATUS_CRC_ERROR";
    case 0xC0000040: return (PUCHAR)"STATUS_SECTION_TOO_BIG";
    case 0xC0000041: return (PUCHAR)"STATUS_PORT_CONNECTION_REFUSED";
    case 0xC0000042: return (PUCHAR)"STATUS_INVALID_PORT_HANDLE";
    case 0xC0000043: return (PUCHAR)"STATUS_SHARING_VIOLATION";
    case 0xC0000044: return (PUCHAR)"STATUS_QUOTA_EXCEEDED";
    case 0xC0000045: return (PUCHAR)"STATUS_INVALID_PAGE_PROTECTION";
    case 0xC0000046: return (PUCHAR)"STATUS_MUTANT_NOT_OWNED";
    case 0xC0000047: return (PUCHAR)"STATUS_SEMAPHORE_LIMIT_EXCEEDED";
    case 0xC0000048: return (PUCHAR)"STATUS_PORT_ALREADY_SET";
    case 0xC0000049: return (PUCHAR)"STATUS_SECTION_NOT_IMAGE";
    case 0xC000004A: return (PUCHAR)"STATUS_SUSPEND_COUNT_EXCEEDED";
    case 0xC000004B: return (PUCHAR)"STATUS_THREAD_IS_TERMINATING";
    case 0xC000004C: return (PUCHAR)"STATUS_BAD_WORKING_SET_LIMIT";
    case 0xC000004D: return (PUCHAR)"STATUS_INCOMPATIBLE_FILE_MAP";
    case 0xC000004E: return (PUCHAR)"STATUS_SECTION_PROTECTION";
    case 0xC000004F: return (PUCHAR)"STATUS_EAS_NOT_SUPPORTED";
    case 0xC0000050: return (PUCHAR)"STATUS_EA_TOO_LARGE";
    case 0xC0000051: return (PUCHAR)"STATUS_NONEXISTENT_EA_ENTRY";
    case 0xC0000052: return (PUCHAR)"STATUS_NO_EAS_ON_FILE";
    case 0xC0000053: return (PUCHAR)"STATUS_EA_CORRUPT_ERROR";
    case 0xC0000054: return (PUCHAR)"STATUS_FILE_LOCK_CONFLICT";
    case 0xC0000055: return (PUCHAR)"STATUS_LOCK_NOT_GRANTED";
    case 0xC0000056: return (PUCHAR)"STATUS_DELETE_PENDING";
    case 0xC0000057: return (PUCHAR)"STATUS_CTL_FILE_NOT_SUPPORTED";
    case 0xC0000058: return (PUCHAR)"STATUS_UNKNOWN_REVISION";
    case 0xC0000059: return (PUCHAR)"STATUS_REVISION_MISMATCH";
    case 0xC000005A: return (PUCHAR)"STATUS_INVALID_OWNER";
    case 0xC000005B: return (PUCHAR)"STATUS_INVALID_PRIMARY_GROUP";
    case 0xC000005C: return (PUCHAR)"STATUS_NO_IMPERSONATION_TOKEN";
    case 0xC000005D: return (PUCHAR)"STATUS_CANT_DISABLE_MANDATORY";
    case 0xC000005E: return (PUCHAR)"STATUS_NO_LOGON_SERVERS";
    case 0xC000005F: return (PUCHAR)"STATUS_NO_SUCH_LOGON_SESSION";
    case 0xC0000060: return (PUCHAR)"STATUS_NO_SUCH_PRIVILEGE";
    case 0xC0000061: return (PUCHAR)"STATUS_PRIVILEGE_NOT_HELD";
    case 0xC0000062: return (PUCHAR)"STATUS_INVALID_ACCOUNT_NAME";
    case 0xC0000063: return (PUCHAR)"STATUS_USER_EXISTS";
    case 0xC0000064: return (PUCHAR)"STATUS_NO_SUCH_USER";
    case 0xC0000065: return (PUCHAR)"STATUS_GROUP_EXISTS";
    case 0xC0000066: return (PUCHAR)"STATUS_NO_SUCH_GROUP";
    case 0xC0000067: return (PUCHAR)"STATUS_MEMBER_IN_GROUP";
    case 0xC0000068: return (PUCHAR)"STATUS_MEMBER_NOT_IN_GROUP";
    case 0xC0000069: return (PUCHAR)"STATUS_LAST_ADMIN";
    case 0xC000006A: return (PUCHAR)"STATUS_WRONG_PASSWORD";
    case 0xC000006B: return (PUCHAR)"STATUS_ILL_FORMED_PASSWORD";
    case 0xC000006C: return (PUCHAR)"STATUS_PASSWORD_RESTRICTION";
    case 0xC000006D: return (PUCHAR)"STATUS_LOGON_FAILURE";
    case 0xC000006E: return (PUCHAR)"STATUS_ACCOUNT_RESTRICTION";
    case 0xC000006F: return (PUCHAR)"STATUS_INVALID_LOGON_HOURS";
    case 0xC0000070: return (PUCHAR)"STATUS_INVALID_WORKSTATION";
    case 0xC0000071: return (PUCHAR)"STATUS_PASSWORD_EXPIRED";
    case 0xC0000072: return (PUCHAR)"STATUS_ACCOUNT_DISABLED";
    case 0xC0000073: return (PUCHAR)"STATUS_NONE_MAPPED";
    case 0xC0000074: return (PUCHAR)"STATUS_TOO_MANY_LUIDS_REQUESTED";
    case 0xC0000075: return (PUCHAR)"STATUS_LUIDS_EXHAUSTED";
    case 0xC0000076: return (PUCHAR)"STATUS_INVALID_SUB_AUTHORITY";
    case 0xC0000077: return (PUCHAR)"STATUS_INVALID_ACL";
    case 0xC0000078: return (PUCHAR)"STATUS_INVALID_SID";
    case 0xC0000079: return (PUCHAR)"STATUS_INVALID_SECURITY_DESCR";
    case 0xC000007A: return (PUCHAR)"STATUS_PROCEDURE_NOT_FOUND";
    case 0xC000007B: return (PUCHAR)"STATUS_INVALID_IMAGE_FORMAT";
    case 0xC000007C: return (PUCHAR)"STATUS_NO_TOKEN";
    case 0xC000007D: return (PUCHAR)"STATUS_BAD_INHERITANCE_ACL";
    case 0xC000007E: return (PUCHAR)"STATUS_RANGE_NOT_LOCKED";
    case 0xC000007F: return (PUCHAR)"STATUS_DISK_FULL";
    case 0xC0000080: return (PUCHAR)"STATUS_SERVER_DISABLED";
    case 0xC0000081: return (PUCHAR)"STATUS_SERVER_NOT_DISABLED";
    case 0xC0000082: return (PUCHAR)"STATUS_TOO_MANY_GUIDS_REQUESTED";
    case 0xC0000083: return (PUCHAR)"STATUS_GUIDS_EXHAUSTED";
    case 0xC0000084: return (PUCHAR)"STATUS_INVALID_ID_AUTHORITY";
    case 0xC0000085: return (PUCHAR)"STATUS_AGENTS_EXHAUSTED";
    case 0xC0000086: return (PUCHAR)"STATUS_INVALID_VOLUME_LABEL";
    case 0xC0000087: return (PUCHAR)"STATUS_SECTION_NOT_EXTENDED";
    case 0xC0000088: return (PUCHAR)"STATUS_NOT_MAPPED_DATA";
    case 0xC0000089: return (PUCHAR)"STATUS_RESOURCE_DATA_NOT_FOUND";
    case 0xC000008A: return (PUCHAR)"STATUS_RESOURCE_TYPE_NOT_FOUND";
    case 0xC000008B: return (PUCHAR)"STATUS_RESOURCE_NAME_NOT_FOUND";
    case 0xC000008C: return (PUCHAR)"STATUS_ARRAY_BOUNDS_EXCEEDED";
    case 0xC000008D: return (PUCHAR)"STATUS_FLOAT_DENORMAL_OPERAND";
    case 0xC000008E: return (PUCHAR)"STATUS_FLOAT_DIVIDE_BY_ZERO";
    case 0xC000008F: return (PUCHAR)"STATUS_FLOAT_INEXACT_RESULT";
    case 0xC0000090: return (PUCHAR)"STATUS_FLOAT_INVALID_OPERATION";
    case 0xC0000091: return (PUCHAR)"STATUS_FLOAT_OVERFLOW";
    case 0xC0000092: return (PUCHAR)"STATUS_FLOAT_STACK_CHECK";
    case 0xC0000093: return (PUCHAR)"STATUS_FLOAT_UNDERFLOW";
    case 0xC0000094: return (PUCHAR)"STATUS_INTEGER_DIVIDE_BY_ZERO";
    case 0xC0000095: return (PUCHAR)"STATUS_INTEGER_OVERFLOW";
    case 0xC0000096: return (PUCHAR)"STATUS_PRIVILEGED_INSTRUCTION";
    case 0xC0000097: return (PUCHAR)"STATUS_TOO_MANY_PAGING_FILES";
    case 0xC0000098: return (PUCHAR)"STATUS_FILE_INVALID";
    case 0xC0000099: return (PUCHAR)"STATUS_ALLOTTED_SPACE_EXCEEDED";
    case 0xC000009A: return (PUCHAR)"STATUS_INSUFFICIENT_RESOURCES";
    case 0xC000009B: return (PUCHAR)"STATUS_DFS_EXIT_PATH_FOUND";
    case 0xC000009C: return (PUCHAR)"STATUS_DEVICE_DATA_ERROR";
    case 0xC000009D: return (PUCHAR)"STATUS_DEVICE_NOT_CONNECTED";
    case 0xC000009E: return (PUCHAR)"STATUS_DEVICE_POWER_FAILURE";
    case 0xC000009F: return (PUCHAR)"STATUS_FREE_VM_NOT_AT_BASE";
    case 0xC00000A0: return (PUCHAR)"STATUS_MEMORY_NOT_ALLOCATED";
    case 0xC00000A1: return (PUCHAR)"STATUS_WORKING_SET_QUOTA";
    case 0xC00000A2: return (PUCHAR)"STATUS_MEDIA_WRITE_PROTECTED";
    case 0xC00000A3: return (PUCHAR)"STATUS_DEVICE_NOT_READY";
    case 0xC00000A4: return (PUCHAR)"STATUS_INVALID_GROUP_ATTRIBUTES";
    case 0xC00000A5: return (PUCHAR)"STATUS_BAD_IMPERSONATION_LEVEL";
    case 0xC00000A6: return (PUCHAR)"STATUS_CANT_OPEN_ANONYMOUS";
    case 0xC00000A7: return (PUCHAR)"STATUS_BAD_VALIDATION_CLASS";
    case 0xC00000A8: return (PUCHAR)"STATUS_BAD_TOKEN_TYPE";
    case 0xC00000A9: return (PUCHAR)"STATUS_BAD_MASTER_BOOT_RECORD";
    case 0xC00000AA: return (PUCHAR)"STATUS_INSTRUCTION_MISALIGNMENT";
    case 0xC00000AB: return (PUCHAR)"STATUS_INSTANCE_NOT_AVAILABLE";
    case 0xC00000AC: return (PUCHAR)"STATUS_PIPE_NOT_AVAILABLE";
    case 0xC00000AD: return (PUCHAR)"STATUS_INVALID_PIPE_STATE";
    case 0xC00000AE: return (PUCHAR)"STATUS_PIPE_BUSY";
    case 0xC00000AF: return (PUCHAR)"STATUS_ILLEGAL_FUNCTION";
    case 0xC00000B0: return (PUCHAR)"STATUS_PIPE_DISCONNECTED";
    case 0xC00000B1: return (PUCHAR)"STATUS_PIPE_CLOSING";
    case 0xC00000B2: return (PUCHAR)"STATUS_PIPE_CONNECTED";
    case 0xC00000B3: return (PUCHAR)"STATUS_PIPE_LISTENING";
    case 0xC00000B4: return (PUCHAR)"STATUS_INVALID_READ_MODE";
    case 0xC00000B5: return (PUCHAR)"STATUS_IO_TIMEOUT";
    case 0xC00000B6: return (PUCHAR)"STATUS_FILE_FORCED_CLOSED";
    case 0xC00000B7: return (PUCHAR)"STATUS_PROFILING_NOT_STARTED";
    case 0xC00000B8: return (PUCHAR)"STATUS_PROFILING_NOT_STOPPED";
    case 0xC00000B9: return (PUCHAR)"STATUS_COULD_NOT_INTERPRET";
    case 0xC00000BA: return (PUCHAR)"STATUS_FILE_IS_A_DIRECTORY";
    case 0xC00000BB: return (PUCHAR)"STATUS_NOT_SUPPORTED";
    case 0xC00000BC: return (PUCHAR)"STATUS_REMOTE_NOT_LISTENING";
    case 0xC00000BD: return (PUCHAR)"STATUS_DUPLICATE_NAME";
    case 0xC00000BE: return (PUCHAR)"STATUS_BAD_NETWORK_PATH";
    case 0xC00000BF: return (PUCHAR)"STATUS_NETWORK_BUSY";
    case 0xC00000C0: return (PUCHAR)"STATUS_DEVICE_DOES_NOT_EXIST";
    case 0xC00000C1: return (PUCHAR)"STATUS_TOO_MANY_COMMANDS";
    case 0xC00000C2: return (PUCHAR)"STATUS_ADAPTER_HARDWARE_ERROR";
    case 0xC00000C3: return (PUCHAR)"STATUS_INVALID_NETWORK_RESPONSE";
    case 0xC00000C4: return (PUCHAR)"STATUS_UNEXPECTED_NETWORK_ERROR";
    case 0xC00000C5: return (PUCHAR)"STATUS_BAD_REMOTE_ADAPTER";
    case 0xC00000C6: return (PUCHAR)"STATUS_PRINT_QUEUE_FULL";
    case 0xC00000C7: return (PUCHAR)"STATUS_NO_SPOOL_SPACE";
    case 0xC00000C8: return (PUCHAR)"STATUS_PRINT_CANCELLED";
    case 0xC00000C9: return (PUCHAR)"STATUS_NETWORK_NAME_DELETED";
    case 0xC00000CA: return (PUCHAR)"STATUS_NETWORK_ACCESS_DENIED";
    case 0xC00000CB: return (PUCHAR)"STATUS_BAD_DEVICE_TYPE";
    case 0xC00000CC: return (PUCHAR)"STATUS_BAD_NETWORK_NAME";
    case 0xC00000CD: return (PUCHAR)"STATUS_TOO_MANY_NAMES";
    case 0xC00000CE: return (PUCHAR)"STATUS_TOO_MANY_SESSIONS";
    case 0xC00000CF: return (PUCHAR)"STATUS_SHARING_PAUSED";
    case 0xC00000D0: return (PUCHAR)"STATUS_REQUEST_NOT_ACCEPTED";
    case 0xC00000D1: return (PUCHAR)"STATUS_REDIRECTOR_PAUSED";
    case 0xC00000D2: return (PUCHAR)"STATUS_NET_WRITE_FAULT";
    case 0xC00000D3: return (PUCHAR)"STATUS_PROFILING_AT_LIMIT";
    case 0xC00000D4: return (PUCHAR)"STATUS_NOT_SAME_DEVICE";
    case 0xC00000D5: return (PUCHAR)"STATUS_FILE_RENAMED";
    case 0xC00000D6: return (PUCHAR)"STATUS_VIRTUAL_CIRCUIT_CLOSED";
    case 0xC00000D7: return (PUCHAR)"STATUS_NO_SECURITY_ON_OBJECT";
    case 0xC00000D8: return (PUCHAR)"STATUS_CANT_WAIT";
    case 0xC00000D9: return (PUCHAR)"STATUS_PIPE_EMPTY";
    case 0xC00000DA: return (PUCHAR)"STATUS_CANT_ACCESS_DOMAIN_INFO";
    case 0xC00000DB: return (PUCHAR)"STATUS_CANT_TERMINATE_SELF";
    case 0xC00000DC: return (PUCHAR)"STATUS_INVALID_SERVER_STATE";
    case 0xC00000DD: return (PUCHAR)"STATUS_INVALID_DOMAIN_STATE";
    case 0xC00000DE: return (PUCHAR)"STATUS_INVALID_DOMAIN_ROLE";
    case 0xC00000DF: return (PUCHAR)"STATUS_NO_SUCH_DOMAIN";
    case 0xC00000E0: return (PUCHAR)"STATUS_DOMAIN_EXISTS";
    case 0xC00000E1: return (PUCHAR)"STATUS_DOMAIN_LIMIT_EXCEEDED";
    case 0xC00000E2: return (PUCHAR)"STATUS_OPLOCK_NOT_GRANTED";
    case 0xC00000E3: return (PUCHAR)"STATUS_INVALID_OPLOCK_PROTOCOL";
    case 0xC00000E4: return (PUCHAR)"STATUS_INTERNAL_DB_CORRUPTION";
    case 0xC00000E5: return (PUCHAR)"STATUS_INTERNAL_ERROR";
    case 0xC00000E6: return (PUCHAR)"STATUS_GENERIC_NOT_MAPPED";
    case 0xC00000E7: return (PUCHAR)"STATUS_BAD_DESCRIPTOR_FORMAT";
    case 0xC00000E8: return (PUCHAR)"STATUS_INVALID_USER_BUFFER";
    case 0xC00000E9: return (PUCHAR)"STATUS_UNEXPECTED_IO_ERROR";
    case 0xC00000EA: return (PUCHAR)"STATUS_UNEXPECTED_MM_CREATE_ERR";
    case 0xC00000EB: return (PUCHAR)"STATUS_UNEXPECTED_MM_MAP_ERROR";
    case 0xC00000EC: return (PUCHAR)"STATUS_UNEXPECTED_MM_EXTEND_ERR";
    case 0xC00000ED: return (PUCHAR)"STATUS_NOT_LOGON_PROCESS";
    case 0xC00000EE: return (PUCHAR)"STATUS_LOGON_SESSION_EXISTS";
    case 0xC00000EF: return (PUCHAR)"STATUS_INVALID_PARAMETER_1";
    case 0xC00000F0: return (PUCHAR)"STATUS_INVALID_PARAMETER_2";
    case 0xC00000F1: return (PUCHAR)"STATUS_INVALID_PARAMETER_3";
    case 0xC00000F2: return (PUCHAR)"STATUS_INVALID_PARAMETER_4";
    case 0xC00000F3: return (PUCHAR)"STATUS_INVALID_PARAMETER_5";
    case 0xC00000F4: return (PUCHAR)"STATUS_INVALID_PARAMETER_6";
    case 0xC00000F5: return (PUCHAR)"STATUS_INVALID_PARAMETER_7";
    case 0xC00000F6: return (PUCHAR)"STATUS_INVALID_PARAMETER_8";
    case 0xC00000F7: return (PUCHAR)"STATUS_INVALID_PARAMETER_9";
    case 0xC00000F8: return (PUCHAR)"STATUS_INVALID_PARAMETER_10";
    case 0xC00000F9: return (PUCHAR)"STATUS_INVALID_PARAMETER_11";
    case 0xC00000FA: return (PUCHAR)"STATUS_INVALID_PARAMETER_12";
    case 0xC00000FB: return (PUCHAR)"STATUS_REDIRECTOR_NOT_STARTED";
    case 0xC00000FC: return (PUCHAR)"STATUS_REDIRECTOR_STARTED";
    case 0xC00000FD: return (PUCHAR)"STATUS_STACK_OVERFLOW";
    case 0xC00000FE: return (PUCHAR)"STATUS_NO_SUCH_PACKAGE";
    case 0xC00000FF: return (PUCHAR)"STATUS_BAD_FUNCTION_TABLE";
    case 0xC0000100: return (PUCHAR)"STATUS_VARIABLE_NOT_FOUND";
    case 0xC0000101: return (PUCHAR)"STATUS_DIRECTORY_NOT_EMPTY";
    case 0xC0000102: return (PUCHAR)"STATUS_FILE_CORRUPT_ERROR";
    case 0xC0000103: return (PUCHAR)"STATUS_NOT_A_DIRECTORY";
    case 0xC0000104: return (PUCHAR)"STATUS_BAD_LOGON_SESSION_STATE";
    case 0xC0000105: return (PUCHAR)"STATUS_LOGON_SESSION_COLLISION";
    case 0xC0000106: return (PUCHAR)"STATUS_NAME_TOO_LONG";
    case 0xC0000107: return (PUCHAR)"STATUS_FILES_OPEN";
    case 0xC0000108: return (PUCHAR)"STATUS_CONNECTION_IN_USE";
    case 0xC0000109: return (PUCHAR)"STATUS_MESSAGE_NOT_FOUND";
    case 0xC000010A: return (PUCHAR)"STATUS_PROCESS_IS_TERMINATING";
    case 0xC000010B: return (PUCHAR)"STATUS_INVALID_LOGON_TYPE";
    case 0xC000010C: return (PUCHAR)"STATUS_NO_GUID_TRANSLATION";
    case 0xC000010D: return (PUCHAR)"STATUS_CANNOT_IMPERSONATE";
    case 0xC000010E: return (PUCHAR)"STATUS_IMAGE_ALREADY_LOADED";
    case 0xC000010F: return (PUCHAR)"STATUS_ABIOS_NOT_PRESENT";
    case 0xC0000110: return (PUCHAR)"STATUS_ABIOS_LID_NOT_EXIST";
    case 0xC0000111: return (PUCHAR)"STATUS_ABIOS_LID_ALREADY_OWNED";
    case 0xC0000112: return (PUCHAR)"STATUS_ABIOS_NOT_LID_OWNER";
    case 0xC0000113: return (PUCHAR)"STATUS_ABIOS_INVALID_COMMAND";
    case 0xC0000114: return (PUCHAR)"STATUS_ABIOS_INVALID_LID";
    case 0xC0000115: return (PUCHAR)"STATUS_ABIOS_SELECTOR_NOT_AVAILABLE";
    case 0xC0000116: return (PUCHAR)"STATUS_ABIOS_INVALID_SELECTOR";
    case 0xC0000117: return (PUCHAR)"STATUS_NO_LDT";
    case 0xC0000118: return (PUCHAR)"STATUS_INVALID_LDT_SIZE";
    case 0xC0000119: return (PUCHAR)"STATUS_INVALID_LDT_OFFSET";
    case 0xC000011A: return (PUCHAR)"STATUS_INVALID_LDT_DESCRIPTOR";
    case 0xC000011B: return (PUCHAR)"STATUS_INVALID_IMAGE_NE_FORMAT";
    case 0xC000011C: return (PUCHAR)"STATUS_RXACT_INVALID_STATE";
    case 0xC000011D: return (PUCHAR)"STATUS_RXACT_COMMIT_FAILURE";
    case 0xC000011E: return (PUCHAR)"STATUS_MAPPED_FILE_SIZE_ZERO";
    case 0xC000011F: return (PUCHAR)"STATUS_TOO_MANY_OPENED_FILES";
    case 0xC0000120: return (PUCHAR)"STATUS_CANCELLED";
    case 0xC0000121: return (PUCHAR)"STATUS_CANNOT_DELETE";
    case 0xC0000122: return (PUCHAR)"STATUS_INVALID_COMPUTER_NAME";
    case 0xC0000123: return (PUCHAR)"STATUS_FILE_DELETED";
    case 0xC0000124: return (PUCHAR)"STATUS_SPECIAL_ACCOUNT";
    case 0xC0000125: return (PUCHAR)"STATUS_SPECIAL_GROUP";
    case 0xC0000126: return (PUCHAR)"STATUS_SPECIAL_USER";
    case 0xC0000127: return (PUCHAR)"STATUS_MEMBERS_PRIMARY_GROUP";
    case 0xC0000128: return (PUCHAR)"STATUS_FILE_CLOSED";
    case 0xC0000129: return (PUCHAR)"STATUS_TOO_MANY_THREADS";
    case 0xC000012A: return (PUCHAR)"STATUS_THREAD_NOT_IN_PROCESS";
    case 0xC000012B: return (PUCHAR)"STATUS_TOKEN_ALREADY_IN_USE";
    case 0xC000012C: return (PUCHAR)"STATUS_PAGEFILE_QUOTA_EXCEEDED";
    case 0xC000012D: return (PUCHAR)"STATUS_COMMITMENT_LIMIT";
    case 0xC000012E: return (PUCHAR)"STATUS_INVALID_IMAGE_LE_FORMAT";
    case 0xC000012F: return (PUCHAR)"STATUS_INVALID_IMAGE_NOT_MZ";
    case 0xC0000130: return (PUCHAR)"STATUS_INVALID_IMAGE_PROTECT";
    case 0xC0000131: return (PUCHAR)"STATUS_INVALID_IMAGE_WIN_16";
    case 0xC0000132: return (PUCHAR)"STATUS_LOGON_SERVER_CONFLICT";
    case 0xC0000133: return (PUCHAR)"STATUS_TIME_DIFFERENCE_AT_DC";
    case 0xC0000134: return (PUCHAR)"STATUS_SYNCHRONIZATION_REQUIRED";
    case 0xC0000135: return (PUCHAR)"STATUS_DLL_NOT_FOUND";
    case 0xC0000136: return (PUCHAR)"STATUS_OPEN_FAILED";
    case 0xC0000137: return (PUCHAR)"STATUS_IO_PRIVILEGE_FAILED";
    case 0xC0000138: return (PUCHAR)"STATUS_ORDINAL_NOT_FOUND";
    case 0xC0000139: return (PUCHAR)"STATUS_ENTRYPOINT_NOT_FOUND";
    case 0xC000013A: return (PUCHAR)"STATUS_CONTROL_C_EXIT";
    case 0xC000013B: return (PUCHAR)"STATUS_LOCAL_DISCONNECT";
    case 0xC000013C: return (PUCHAR)"STATUS_REMOTE_DISCONNECT";
    case 0xC000013D: return (PUCHAR)"STATUS_REMOTE_RESOURCES";
    case 0xC000013E: return (PUCHAR)"STATUS_LINK_FAILED";
    case 0xC000013F: return (PUCHAR)"STATUS_LINK_TIMEOUT";
    case 0xC0000140: return (PUCHAR)"STATUS_INVALID_CONNECTION";
    case 0xC0000141: return (PUCHAR)"STATUS_INVALID_ADDRESS";
    case 0xC0000142: return (PUCHAR)"STATUS_DLL_INIT_FAILED";
    case 0xC0000143: return (PUCHAR)"STATUS_MISSING_SYSTEMFILE";
    case 0xC0000144: return (PUCHAR)"STATUS_UNHANDLED_EXCEPTION";
    case 0xC0000145: return (PUCHAR)"STATUS_APP_INIT_FAILURE";
    case 0xC0000146: return (PUCHAR)"STATUS_PAGEFILE_CREATE_FAILED";
    case 0xC0000147: return (PUCHAR)"STATUS_NO_PAGEFILE";
    case 0xC0000148: return (PUCHAR)"STATUS_INVALID_LEVEL";
    case 0xC0000149: return (PUCHAR)"STATUS_WRONG_PASSWORD_CORE";
    case 0xC000014A: return (PUCHAR)"STATUS_ILLEGAL_FLOAT_CONTEXT";
    case 0xC000014B: return (PUCHAR)"STATUS_PIPE_BROKEN";
    case 0xC000014C: return (PUCHAR)"STATUS_REGISTRY_CORRUPT";
    case 0xC000014D: return (PUCHAR)"STATUS_REGISTRY_IO_FAILED";
    case 0xC000014E: return (PUCHAR)"STATUS_NO_EVENT_PAIR";
    case 0xC000014F: return (PUCHAR)"STATUS_UNRECOGNIZED_VOLUME";
    case 0xC0000150: return (PUCHAR)"STATUS_SERIAL_NO_DEVICE_INITED";
    case 0xC0000151: return (PUCHAR)"STATUS_NO_SUCH_ALIAS";
    case 0xC0000152: return (PUCHAR)"STATUS_MEMBER_NOT_IN_ALIAS";
    case 0xC0000153: return (PUCHAR)"STATUS_MEMBER_IN_ALIAS";
    case 0xC0000154: return (PUCHAR)"STATUS_ALIAS_EXISTS";
    case 0xC0000155: return (PUCHAR)"STATUS_LOGON_NOT_GRANTED";
    case 0xC0000156: return (PUCHAR)"STATUS_TOO_MANY_SECRETS";
    case 0xC0000157: return (PUCHAR)"STATUS_SECRET_TOO_LONG";
    case 0xC0000158: return (PUCHAR)"STATUS_INTERNAL_DB_ERROR";
    case 0xC0000159: return (PUCHAR)"STATUS_FULLSCREEN_MODE";
    case 0xC000015A: return (PUCHAR)"STATUS_TOO_MANY_CONTEXT_IDS";
    case 0xC000015B: return (PUCHAR)"STATUS_LOGON_TYPE_NOT_GRANTED";
    case 0xC000015C: return (PUCHAR)"STATUS_NOT_REGISTRY_FILE";
    case 0xC000015D: return (PUCHAR)"STATUS_NT_CROSS_ENCRYPTION_REQUIRED";
    case 0xC000015E: return (PUCHAR)"STATUS_DOMAIN_CTRLR_CONFIG_ERROR";
    case 0xC000015F: return (PUCHAR)"STATUS_FT_MISSING_MEMBER";
    case 0xC0000160: return (PUCHAR)"STATUS_ILL_FORMED_SERVICE_ENTRY";
    case 0xC0000161: return (PUCHAR)"STATUS_ILLEGAL_CHARACTER";
    case 0xC0000162: return (PUCHAR)"STATUS_UNMAPPABLE_CHARACTER";
    case 0xC0000163: return (PUCHAR)"STATUS_UNDEFINED_CHARACTER";
    case 0xC0000164: return (PUCHAR)"STATUS_FLOPPY_VOLUME";
    case 0xC0000165: return (PUCHAR)"STATUS_FLOPPY_ID_MARK_NOT_FOUND";
    case 0xC0000166: return (PUCHAR)"STATUS_FLOPPY_WRONG_CYLINDER";
    case 0xC0000167: return (PUCHAR)"STATUS_FLOPPY_UNKNOWN_ERROR";
    case 0xC0000168: return (PUCHAR)"STATUS_FLOPPY_BAD_REGISTERS";
    case 0xC0000169: return (PUCHAR)"STATUS_DISK_RECALIBRATE_FAILED";
    case 0xC000016A: return (PUCHAR)"STATUS_DISK_OPERATION_FAILED";
    case 0xC000016B: return (PUCHAR)"STATUS_DISK_RESET_FAILED";
    case 0xC000016C: return (PUCHAR)"STATUS_SHARED_IRQ_BUSY";
    case 0xC000016D: return (PUCHAR)"STATUS_FT_ORPHANING";
    case 0xC000016E: return (PUCHAR)"STATUS_BIOS_FAILED_TO_CONNECT_INTERRUPT";
    case 0xC0000172: return (PUCHAR)"STATUS_PARTITION_FAILURE";
    case 0xC0000173: return (PUCHAR)"STATUS_INVALID_BLOCK_LENGTH";
    case 0xC0000174: return (PUCHAR)"STATUS_DEVICE_NOT_PARTITIONED";
    case 0xC0000175: return (PUCHAR)"STATUS_UNABLE_TO_LOCK_MEDIA";
    case 0xC0000176: return (PUCHAR)"STATUS_UNABLE_TO_UNLOAD_MEDIA";
    case 0xC0000177: return (PUCHAR)"STATUS_EOM_OVERFLOW";
    case 0xC0000178: return (PUCHAR)"STATUS_NO_MEDIA";
    case 0xC000017A: return (PUCHAR)"STATUS_NO_SUCH_MEMBER";
    case 0xC000017B: return (PUCHAR)"STATUS_INVALID_MEMBER";
    case 0xC000017C: return (PUCHAR)"STATUS_KEY_DELETED";
    case 0xC000017D: return (PUCHAR)"STATUS_NO_LOG_SPACE";
    case 0xC000017E: return (PUCHAR)"STATUS_TOO_MANY_SIDS";
    case 0xC000017F: return (PUCHAR)"STATUS_LM_CROSS_ENCRYPTION_REQUIRED";
    case 0xC0000180: return (PUCHAR)"STATUS_KEY_HAS_CHILDREN";
    case 0xC0000181: return (PUCHAR)"STATUS_CHILD_MUST_BE_VOLATILE";
    case 0xC0000182: return (PUCHAR)"STATUS_DEVICE_CONFIGURATION_ERROR";
    case 0xC0000183: return (PUCHAR)"STATUS_DRIVER_INTERNAL_ERROR";
    case 0xC0000184: return (PUCHAR)"STATUS_INVALID_DEVICE_STATE";
    case 0xC0000185: return (PUCHAR)"STATUS_IO_DEVICE_ERROR";
    case 0xC0000186: return (PUCHAR)"STATUS_DEVICE_PROTOCOL_ERROR";
    case 0xC0000187: return (PUCHAR)"STATUS_BACKUP_CONTROLLER";
    case 0xC0000188: return (PUCHAR)"STATUS_LOG_FILE_FULL";
    case 0xC0000189: return (PUCHAR)"STATUS_TOO_LATE";
    case 0xC000018A: return (PUCHAR)"STATUS_NO_TRUST_LSA_SECRET";
    case 0xC000018B: return (PUCHAR)"STATUS_NO_TRUST_SAM_ACCOUNT";
    case 0xC000018C: return (PUCHAR)"STATUS_TRUSTED_DOMAIN_FAILURE";
    case 0xC000018D: return (PUCHAR)"STATUS_TRUSTED_RELATIONSHIP_FAILURE";
    case 0xC000018E: return (PUCHAR)"STATUS_EVENTLOG_FILE_CORRUPT";
    case 0xC000018F: return (PUCHAR)"STATUS_EVENTLOG_CANT_START";
    case 0xC0000190: return (PUCHAR)"STATUS_TRUST_FAILURE";
    case 0xC0000191: return (PUCHAR)"STATUS_MUTANT_LIMIT_EXCEEDED";
    case 0xC0000192: return (PUCHAR)"STATUS_NETLOGON_NOT_STARTED";
    case 0xC0000193: return (PUCHAR)"STATUS_ACCOUNT_EXPIRED";
    case 0xC0000194: return (PUCHAR)"STATUS_POSSIBLE_DEADLOCK";
    case 0xC0000195: return (PUCHAR)"STATUS_NETWORK_CREDENTIAL_CONFLICT";
    case 0xC0000196: return (PUCHAR)"STATUS_REMOTE_SESSION_LIMIT";
    case 0xC0000197: return (PUCHAR)"STATUS_EVENTLOG_FILE_CHANGED";
    case 0xC0000198: return (PUCHAR)"STATUS_NOLOGON_INTERDOMAIN_TRUST_ACCOUNT";
    case 0xC0000199: return (PUCHAR)"STATUS_NOLOGON_WORKSTATION_TRUST_ACCOUNT";
    case 0xC000019A: return (PUCHAR)"STATUS_NOLOGON_SERVER_TRUST_ACCOUNT";
    case 0xC000019B: return (PUCHAR)"STATUS_DOMAIN_TRUST_INCONSISTENT";
    case 0xC000019C: return (PUCHAR)"STATUS_FS_DRIVER_REQUIRED";
    case 0xC0000202: return (PUCHAR)"STATUS_NO_USER_SESSION_KEY";
    case 0xC0000203: return (PUCHAR)"STATUS_USER_SESSION_DELETED";
    case 0xC0000204: return (PUCHAR)"STATUS_RESOURCE_LANG_NOT_FOUND";
    case 0xC0000205: return (PUCHAR)"STATUS_INSUFF_SERVER_RESOURCES";
    case 0xC0000206: return (PUCHAR)"STATUS_INVALID_BUFFER_SIZE";
    case 0xC0000207: return (PUCHAR)"STATUS_INVALID_ADDRESS_COMPONENT";
    case 0xC0000208: return (PUCHAR)"STATUS_INVALID_ADDRESS_WILDCARD";
    case 0xC0000209: return (PUCHAR)"STATUS_TOO_MANY_ADDRESSES";
    case 0xC000020A: return (PUCHAR)"STATUS_ADDRESS_ALREADY_EXISTS";
    case 0xC000020B: return (PUCHAR)"STATUS_ADDRESS_CLOSED";
    case 0xC000020C: return (PUCHAR)"STATUS_CONNECTION_DISCONNECTED";
    case 0xC000020D: return (PUCHAR)"STATUS_CONNECTION_RESET";
    case 0xC000020E: return (PUCHAR)"STATUS_TOO_MANY_NODES";
    case 0xC000020F: return (PUCHAR)"STATUS_TRANSACTION_ABORTED";
    case 0xC0000210: return (PUCHAR)"STATUS_TRANSACTION_TIMED_OUT";
    case 0xC0000211: return (PUCHAR)"STATUS_TRANSACTION_NO_RELEASE";
    case 0xC0000212: return (PUCHAR)"STATUS_TRANSACTION_NO_MATCH";
    case 0xC0000213: return (PUCHAR)"STATUS_TRANSACTION_RESPONDED";
    case 0xC0000214: return (PUCHAR)"STATUS_TRANSACTION_INVALID_ID";
    case 0xC0000215: return (PUCHAR)"STATUS_TRANSACTION_INVALID_TYPE";
    case 0xC0000216: return (PUCHAR)"STATUS_NOT_SERVER_SESSION";
    case 0xC0000217: return (PUCHAR)"STATUS_NOT_CLIENT_SESSION";
    case 0xC0000218: return (PUCHAR)"STATUS_CANNOT_LOAD_REGISTRY_FILE";
    case 0xC0000219: return (PUCHAR)"STATUS_DEBUG_ATTACH_FAILED";
    case 0xC000021A: return (PUCHAR)"STATUS_SYSTEM_PROCESS_TERMINATED";
    case 0xC000021B: return (PUCHAR)"STATUS_DATA_NOT_ACCEPTED";
    case 0xC000021C: return (PUCHAR)"STATUS_NO_BROWSER_SERVERS_FOUND";
    case 0xC000021D: return (PUCHAR)"STATUS_VDM_HARD_ERROR";
    case 0xC000021E: return (PUCHAR)"STATUS_DRIVER_CANCEL_TIMEOUT";
    case 0xC000021F: return (PUCHAR)"STATUS_REPLY_MESSAGE_MISMATCH";
    case 0xC0000220: return (PUCHAR)"STATUS_MAPPED_ALIGNMENT";
    case 0xC0000221: return (PUCHAR)"STATUS_IMAGE_CHECKSUM_MISMATCH";
    case 0xC0000222: return (PUCHAR)"STATUS_LOST_WRITEBEHIND_DATA";
    case 0xC0000223: return (PUCHAR)"STATUS_CLIENT_SERVER_PARAMETERS_INVALID";
    case 0xC0000224: return (PUCHAR)"STATUS_PASSWORD_MUST_CHANGE";
    case 0xC0000225: return (PUCHAR)"STATUS_NOT_FOUND";
    case 0xC0000226: return (PUCHAR)"STATUS_NOT_TINY_STREAM";
    case 0xC0000227: return (PUCHAR)"STATUS_RECOVERY_FAILURE";
    case 0xC0000228: return (PUCHAR)"STATUS_STACK_OVERFLOW_READ";
    case 0xC0000229: return (PUCHAR)"STATUS_FAIL_CHECK";
    case 0xC000022A: return (PUCHAR)"STATUS_DUPLICATE_OBJECTID";
    case 0xC000022B: return (PUCHAR)"STATUS_OBJECTID_EXISTS";
    case 0xC000022C: return (PUCHAR)"STATUS_CONVERT_TO_LARGE";
    case 0xC000022D: return (PUCHAR)"STATUS_RETRY";
    case 0xC000022E: return (PUCHAR)"STATUS_FOUND_OUT_OF_SCOPE";
    case 0xC000022F: return (PUCHAR)"STATUS_ALLOCATE_BUCKET";
    case 0xC0000230: return (PUCHAR)"STATUS_PROPSET_NOT_FOUND";
    case 0xC0000231: return (PUCHAR)"STATUS_MARSHALL_OVERFLOW";
    case 0xC0000232: return (PUCHAR)"STATUS_INVALID_VARIANT";
    case 0xC0000233: return (PUCHAR)"STATUS_DOMAIN_CONTROLLER_NOT_FOUND";
    case 0xC0000234: return (PUCHAR)"STATUS_ACCOUNT_LOCKED_OUT";
    case 0xC0000235: return (PUCHAR)"STATUS_HANDLE_NOT_CLOSABLE";
    case 0xC0000236: return (PUCHAR)"STATUS_CONNECTION_REFUSED";
    case 0xC0000237: return (PUCHAR)"STATUS_GRACEFUL_DISCONNECT";
    case 0xC0000238: return (PUCHAR)"STATUS_ADDRESS_ALREADY_ASSOCIATED";
    case 0xC0000239: return (PUCHAR)"STATUS_ADDRESS_NOT_ASSOCIATED";
    case 0xC000023A: return (PUCHAR)"STATUS_CONNECTION_INVALID";
    case 0xC000023B: return (PUCHAR)"STATUS_CONNECTION_ACTIVE";
    case 0xC000023C: return (PUCHAR)"STATUS_NETWORK_UNREACHABLE";
    case 0xC000023D: return (PUCHAR)"STATUS_HOST_UNREACHABLE";
    case 0xC000023E: return (PUCHAR)"STATUS_PROTOCOL_UNREACHABLE";
    case 0xC000023F: return (PUCHAR)"STATUS_PORT_UNREACHABLE";
    case 0xC0000240: return (PUCHAR)"STATUS_REQUEST_ABORTED";
    case 0xC0000241: return (PUCHAR)"STATUS_CONNECTION_ABORTED";
    case 0xC0000242: return (PUCHAR)"STATUS_BAD_COMPRESSION_BUFFER";
    case 0xC0000243: return (PUCHAR)"STATUS_USER_MAPPED_FILE";
    case 0xC0000244: return (PUCHAR)"STATUS_AUDIT_FAILED";
    case 0xC0000245: return (PUCHAR)"STATUS_TIMER_RESOLUTION_NOT_SET";
    case 0xC0000246: return (PUCHAR)"STATUS_CONNECTION_COUNT_LIMIT";
    case 0xC0000247: return (PUCHAR)"STATUS_LOGIN_TIME_RESTRICTION";
    case 0xC0000248: return (PUCHAR)"STATUS_LOGIN_WKSTA_RESTRICTION";
    case 0xC0000249: return (PUCHAR)"STATUS_IMAGE_MP_UP_MISMATCH";
    case 0xC0000250: return (PUCHAR)"STATUS_INSUFFICIENT_LOGON_INFO";
    case 0xC0000251: return (PUCHAR)"STATUS_BAD_DLL_ENTRYPOINT";
    case 0xC0000252: return (PUCHAR)"STATUS_BAD_SERVICE_ENTRYPOINT";
    case 0xC0000253: return (PUCHAR)"STATUS_LPC_REPLY_LOST";
    case 0xC0000254: return (PUCHAR)"STATUS_IP_ADDRESS_CONFLICT1";
    case 0xC0000255: return (PUCHAR)"STATUS_IP_ADDRESS_CONFLICT2";
    case 0xC0000256: return (PUCHAR)"STATUS_REGISTRY_QUOTA_LIMIT";
    case 0xC0000257: return (PUCHAR)"STATUS_PATH_NOT_COVERED";
    case 0xC0000258: return (PUCHAR)"STATUS_NO_CALLBACK_ACTIVE";
    case 0xC0000259: return (PUCHAR)"STATUS_LICENSE_QUOTA_EXCEEDED";
    case 0xC000025A: return (PUCHAR)"STATUS_PWD_TOO_SHORT";
    case 0xC000025B: return (PUCHAR)"STATUS_PWD_TOO_RECENT";
    case 0xC000025C: return (PUCHAR)"STATUS_PWD_HISTORY_CONFLICT";
    case 0xC000025E: return (PUCHAR)"STATUS_PLUGPLAY_NO_DEVICE";
    case 0xC000025F: return (PUCHAR)"STATUS_UNSUPPORTED_COMPRESSION";
    case 0xC0000260: return (PUCHAR)"STATUS_INVALID_HW_PROFILE";
    case 0xC0000261: return (PUCHAR)"STATUS_INVALID_PLUGPLAY_DEVICE_PATH";
    case 0xC0000262: return (PUCHAR)"STATUS_DRIVER_ORDINAL_NOT_FOUND";
    case 0xC0000263: return (PUCHAR)"STATUS_DRIVER_ENTRYPOINT_NOT_FOUND";
    case 0xC0000264: return (PUCHAR)"STATUS_RESOURCE_NOT_OWNED";
    case 0xC0000265: return (PUCHAR)"STATUS_TOO_MANY_LINKS";
    case 0xC0000266: return (PUCHAR)"STATUS_QUOTA_LIST_INCONSISTENT";
    case 0xC0000267: return (PUCHAR)"STATUS_FILE_IS_OFFLINE";
    case 0xC0000268: return (PUCHAR)"STATUS_EVALUATION_EXPIRATION";
    case 0xC0000269: return (PUCHAR)"STATUS_ILLEGAL_DLL_RELOCATION";
    case 0xC000026A: return (PUCHAR)"STATUS_LICENSE_VIOLATION";
    case 0xC000026B: return (PUCHAR)"STATUS_DLL_INIT_FAILED_LOGOFF";
    case 0xC000026C: return (PUCHAR)"STATUS_DRIVER_UNABLE_TO_LOAD";
    case 0xC000026D: return (PUCHAR)"STATUS_DFS_UNAVAILABLE";
    case 0xC000026E: return (PUCHAR)"STATUS_VOLUME_DISMOUNTED";
    case 0xC000026F: return (PUCHAR)"STATUS_WX86_INTERNAL_ERROR";
    case 0xC0000270: return (PUCHAR)"STATUS_WX86_FLOAT_STACK_CHECK";
    case 0xC0000271: return (PUCHAR)"STATUS_VALIDATE_CONTINUE";
    case 0xC0000272: return (PUCHAR)"STATUS_NO_MATCH";
    case 0xC0000273: return (PUCHAR)"STATUS_NO_MORE_MATCHES";
    case 0xC0000275: return (PUCHAR)"STATUS_NOT_A_REPARSE_POINT";
    case 0xC0000276: return (PUCHAR)"STATUS_IO_REPARSE_TAG_INVALID";
    case 0xC0000277: return (PUCHAR)"STATUS_IO_REPARSE_TAG_MISMATCH";
    case 0xC0000278: return (PUCHAR)"STATUS_IO_REPARSE_DATA_INVALID";
    case 0xC0000279: return (PUCHAR)"STATUS_IO_REPARSE_TAG_NOT_HANDLED";
    case 0xC0000280: return (PUCHAR)"STATUS_REPARSE_POINT_NOT_RESOLVED";
    case 0xC0000281: return (PUCHAR)"STATUS_DIRECTORY_IS_A_REPARSE_POINT";
    case 0xC0000282: return (PUCHAR)"STATUS_RANGE_LIST_CONFLICT";
    case 0xC0000283: return (PUCHAR)"STATUS_SOURCE_ELEMENT_EMPTY";
    case 0xC0000284: return (PUCHAR)"STATUS_DESTINATION_ELEMENT_FULL";
    case 0xC0000285: return (PUCHAR)"STATUS_ILLEGAL_ELEMENT_ADDRESS";
    case 0xC0000286: return (PUCHAR)"STATUS_MAGAZINE_NOT_PRESENT";
    case 0xC0000287: return (PUCHAR)"STATUS_REINITIALIZATION_NEEDED";
    case 0x80000288: return (PUCHAR)"STATUS_DEVICE_REQUIRES_CLEANING";
    case 0x80000289: return (PUCHAR)"STATUS_DEVICE_DOOR_OPEN";
    case 0xC000028A: return (PUCHAR)"STATUS_ENCRYPTION_FAILED";
    case 0xC000028B: return (PUCHAR)"STATUS_DECRYPTION_FAILED";
    case 0xC000028C: return (PUCHAR)"STATUS_RANGE_NOT_FOUND";
    case 0xC000028D: return (PUCHAR)"STATUS_NO_RECOVERY_POLICY";
    case 0xC000028E: return (PUCHAR)"STATUS_NO_EFS";
    case 0xC000028F: return (PUCHAR)"STATUS_WRONG_EFS";
    case 0xC0000290: return (PUCHAR)"STATUS_NO_USER_KEYS";
    case 0xC0000291: return (PUCHAR)"STATUS_FILE_NOT_ENCRYPTED";
    case 0xC0000292: return (PUCHAR)"STATUS_NOT_EXPORT_FORMAT";
    case 0xC0000293: return (PUCHAR)"STATUS_FILE_ENCRYPTED";
    case 0x40000294: return (PUCHAR)"STATUS_WAKE_SYSTEM";
    case 0xC0000295: return (PUCHAR)"STATUS_WMI_GUID_NOT_FOUND";
    case 0xC0000296: return (PUCHAR)"STATUS_WMI_INSTANCE_NOT_FOUND";
    case 0xC0000297: return (PUCHAR)"STATUS_WMI_ITEMID_NOT_FOUND";
    case 0xC0000298: return (PUCHAR)"STATUS_WMI_TRY_AGAIN";
    case 0xC0000299: return (PUCHAR)"STATUS_SHARED_POLICY";
    case 0xC000029A: return (PUCHAR)"STATUS_POLICY_OBJECT_NOT_FOUND";
    case 0xC000029B: return (PUCHAR)"STATUS_POLICY_ONLY_IN_DS";
    case 0xC000029C: return (PUCHAR)"STATUS_VOLUME_NOT_UPGRADED";
    case 0xC000029D: return (PUCHAR)"STATUS_REMOTE_STORAGE_NOT_ACTIVE";
    case 0xC000029E: return (PUCHAR)"STATUS_REMOTE_STORAGE_MEDIA_ERROR";
    case 0xC000029F: return (PUCHAR)"STATUS_NO_TRACKING_SERVICE";
    case 0xC00002A0: return (PUCHAR)"STATUS_SERVER_SID_MISMATCH";
    case 0xC00002A1: return (PUCHAR)"STATUS_DS_NO_ATTRIBUTE_OR_VALUE";
    case 0xC00002A2: return (PUCHAR)"STATUS_DS_INVALID_ATTRIBUTE_SYNTAX";
    case 0xC00002A3: return (PUCHAR)"STATUS_DS_ATTRIBUTE_TYPE_UNDEFINED";
    case 0xC00002A4: return (PUCHAR)"STATUS_DS_ATTRIBUTE_OR_VALUE_EXISTS";
    case 0xC00002A5: return (PUCHAR)"STATUS_DS_BUSY";
    case 0xC00002A6: return (PUCHAR)"STATUS_DS_UNAVAILABLE";
    case 0xC00002A7: return (PUCHAR)"STATUS_DS_NO_RIDS_ALLOCATED";
    case 0xC00002A8: return (PUCHAR)"STATUS_DS_NO_MORE_RIDS";
    case 0xC00002A9: return (PUCHAR)"STATUS_DS_INCORRECT_ROLE_OWNER";
    case 0xC00002AA: return (PUCHAR)"STATUS_DS_RIDMGR_INIT_ERROR";
    case 0xC00002AB: return (PUCHAR)"STATUS_DS_OBJ_CLASS_VIOLATION";
    case 0xC00002AC: return (PUCHAR)"STATUS_DS_CANT_ON_NON_LEAF";
    case 0xC00002AD: return (PUCHAR)"STATUS_DS_CANT_ON_RDN";
    case 0xC00002AE: return (PUCHAR)"STATUS_DS_CANT_MOD_OBJ_CLASS";
    case 0xC00002AF: return (PUCHAR)"STATUS_DS_CROSS_DOM_MOVE_FAILED";
    case 0xC00002B0: return (PUCHAR)"STATUS_DS_GC_NOT_AVAILABLE";
    case 0xC00002B1: return (PUCHAR)"STATUS_DIRECTORY_SERVICE_REQUIRED";
    case 0xC00002B2: return (PUCHAR)"STATUS_REPARSE_ATTRIBUTE_CONFLICT";
    case 0xC00002B3: return (PUCHAR)"STATUS_CANT_ENABLE_DENY_ONLY";
    case 0xC00002B4: return (PUCHAR)"STATUS_FLOAT_MULTIPLE_FAULTS";
    case 0xC00002B5: return (PUCHAR)"STATUS_FLOAT_MULTIPLE_TRAPS";
    case 0xC00002B6: return (PUCHAR)"STATUS_DEVICE_REMOVED";
    case 0xC00002B7: return (PUCHAR)"STATUS_JOURNAL_DELETE_IN_PROGRESS";
    case 0xC00002B8: return (PUCHAR)"STATUS_JOURNAL_NOT_ACTIVE";
    case 0xC00002B9: return (PUCHAR)"STATUS_NOINTERFACE";
    case 0xC00002C1: return (PUCHAR)"STATUS_DS_ADMIN_LIMIT_EXCEEDED";
    case 0xC00002C2: return (PUCHAR)"STATUS_DRIVER_FAILED_SLEEP";
    case 0xC00002C3: return (PUCHAR)"STATUS_MUTUAL_AUTHENTICATION_FAILED";
    case 0xC00002C4: return (PUCHAR)"STATUS_CORRUPT_SYSTEM_FILE";
    case 0xC00002C5: return (PUCHAR)"STATUS_DATATYPE_MISALIGNMENT_ERROR";
    case 0xC00002C6: return (PUCHAR)"STATUS_WMI_READ_ONLY";
    case 0xC00002C7: return (PUCHAR)"STATUS_WMI_SET_FAILURE";
    case 0xC00002C8: return (PUCHAR)"STATUS_COMMITMENT_MINIMUM";
    case 0xC00002C9: return (PUCHAR)"STATUS_REG_NAT_CONSUMPTION";
    case 0xC00002CA: return (PUCHAR)"STATUS_TRANSPORT_FULL";
    case 0xC00002CB: return (PUCHAR)"STATUS_DS_SAM_INIT_FAILURE";
    case 0xC00002CC: return (PUCHAR)"STATUS_ONLY_IF_CONNECTED";
    case 0xC00002CD: return (PUCHAR)"STATUS_DS_SENSITIVE_GROUP_VIOLATION";
    case 0xC00002CE: return (PUCHAR)"STATUS_PNP_RESTART_ENUMERATION";
    case 0xC00002CF: return (PUCHAR)"STATUS_JOURNAL_ENTRY_DELETED";
    case 0xC00002D0: return (PUCHAR)"STATUS_DS_CANT_MOD_PRIMARYGROUPID";
    case 0xC00002D1: return (PUCHAR)"STATUS_SYSTEM_IMAGE_BAD_SIGNATURE";
    case 0xC00002D2: return (PUCHAR)"STATUS_PNP_REBOOT_REQUIRED";
    case 0xC00002D3: return (PUCHAR)"STATUS_POWER_STATE_INVALID";
    case 0xC00002D4: return (PUCHAR)"STATUS_DS_INVALID_GROUP_TYPE";
    case 0xC00002D5: return (PUCHAR)"STATUS_DS_NO_NEST_GLOBALGROUP_IN_MIXEDDOMAIN";
    case 0xC00002D6: return (PUCHAR)"STATUS_DS_NO_NEST_LOCALGROUP_IN_MIXEDDOMAIN";
    case 0xC00002D7: return (PUCHAR)"STATUS_DS_GLOBAL_CANT_HAVE_LOCAL_MEMBER";
    case 0xC00002D8: return (PUCHAR)"STATUS_DS_GLOBAL_CANT_HAVE_UNIVERSAL_MEMBER";
    case 0xC00002D9: return (PUCHAR)"STATUS_DS_UNIVERSAL_CANT_HAVE_LOCAL_MEMBER";
    case 0xC00002DA: return (PUCHAR)"STATUS_DS_GLOBAL_CANT_HAVE_CROSSDOMAIN_MEMBER";
    case 0xC00002DB: return (PUCHAR)"STATUS_DS_LOCAL_CANT_HAVE_CROSSDOMAIN_LOCAL_MEMBER";
    case 0xC00002DC: return (PUCHAR)"STATUS_DS_HAVE_PRIMARY_MEMBERS";
    case 0xC00002DD: return (PUCHAR)"STATUS_WMI_NOT_SUPPORTED";
    case 0xC00002DE: return (PUCHAR)"STATUS_INSUFFICIENT_POWER";
    case 0xC00002DF: return (PUCHAR)"STATUS_SAM_NEED_BOOTKEY_PASSWORD";
    case 0xC00002E0: return (PUCHAR)"STATUS_SAM_NEED_BOOTKEY_FLOPPY";
    case 0xC00002E1: return (PUCHAR)"STATUS_DS_CANT_START";
    case 0xC00002E2: return (PUCHAR)"STATUS_DS_INIT_FAILURE";
    case 0xC00002E3: return (PUCHAR)"STATUS_SAM_INIT_FAILURE";
    case 0xC00002E4: return (PUCHAR)"STATUS_DS_GC_REQUIRED";
    case 0xC00002E5: return (PUCHAR)"STATUS_DS_LOCAL_MEMBER_OF_LOCAL_ONLY";
    case 0xC00002E6: return (PUCHAR)"STATUS_DS_NO_FPO_IN_UNIVERSAL_GROUPS";
    case 0xC00002E7: return (PUCHAR)"STATUS_DS_MACHINE_ACCOUNT_QUOTA_EXCEEDED";
    case 0xC00002E8: return (PUCHAR)"STATUS_MULTIPLE_FAULT_VIOLATION";
    case 0xC0000300: return (PUCHAR)"STATUS_NOT_SUPPORTED_ON_SBS";
    case 0xC0009898: return (PUCHAR)"STATUS_WOW_ASSERTION";
    case 0xC0010001: return (PUCHAR)"DBG_NO_STATE_CHANGE";
    case 0xC0010002: return (PUCHAR)"DBG_APP_NOT_IDLE";
    case 0xC0020001: return (PUCHAR)"RPC_NT_INVALID_STRING_BINDING";
    case 0xC0020002: return (PUCHAR)"RPC_NT_WRONG_KIND_OF_BINDING";
    case 0xC0020003: return (PUCHAR)"RPC_NT_INVALID_BINDING";
    case 0xC0020004: return (PUCHAR)"RPC_NT_PROTSEQ_NOT_SUPPORTED";
    case 0xC0020005: return (PUCHAR)"RPC_NT_INVALID_RPC_PROTSEQ";
    case 0xC0020006: return (PUCHAR)"RPC_NT_INVALID_STRING_UUID";
    case 0xC0020007: return (PUCHAR)"RPC_NT_INVALID_ENDPOINT_FORMAT";
    case 0xC0020008: return (PUCHAR)"RPC_NT_INVALID_NET_ADDR";
    case 0xC0020009: return (PUCHAR)"RPC_NT_NO_ENDPOINT_FOUND";
    case 0xC002000A: return (PUCHAR)"RPC_NT_INVALID_TIMEOUT";
    case 0xC002000B: return (PUCHAR)"RPC_NT_OBJECT_NOT_FOUND";
    case 0xC002000C: return (PUCHAR)"RPC_NT_ALREADY_REGISTERED";
    case 0xC002000D: return (PUCHAR)"RPC_NT_TYPE_ALREADY_REGISTERED";
    case 0xC002000E: return (PUCHAR)"RPC_NT_ALREADY_LISTENING";
    case 0xC002000F: return (PUCHAR)"RPC_NT_NO_PROTSEQS_REGISTERED";
    case 0xC0020010: return (PUCHAR)"RPC_NT_NOT_LISTENING";
    case 0xC0020011: return (PUCHAR)"RPC_NT_UNKNOWN_MGR_TYPE";
    case 0xC0020012: return (PUCHAR)"RPC_NT_UNKNOWN_IF";
    case 0xC0020013: return (PUCHAR)"RPC_NT_NO_BINDINGS";
    case 0xC0020014: return (PUCHAR)"RPC_NT_NO_PROTSEQS";
    case 0xC0020015: return (PUCHAR)"RPC_NT_CANT_CREATE_ENDPOINT";
    case 0xC0020016: return (PUCHAR)"RPC_NT_OUT_OF_RESOURCES";
    case 0xC0020017: return (PUCHAR)"RPC_NT_SERVER_UNAVAILABLE";
    case 0xC0020018: return (PUCHAR)"RPC_NT_SERVER_TOO_BUSY";
    case 0xC0020019: return (PUCHAR)"RPC_NT_INVALID_NETWORK_OPTIONS";
    case 0xC002001A: return (PUCHAR)"RPC_NT_NO_CALL_ACTIVE";
    case 0xC002001B: return (PUCHAR)"RPC_NT_CALL_FAILED";
    case 0xC002001C: return (PUCHAR)"RPC_NT_CALL_FAILED_DNE";
    case 0xC002001D: return (PUCHAR)"RPC_NT_PROTOCOL_ERROR";
    case 0xC002001F: return (PUCHAR)"RPC_NT_UNSUPPORTED_TRANS_SYN";
    case 0xC0020021: return (PUCHAR)"RPC_NT_UNSUPPORTED_TYPE";
    case 0xC0020022: return (PUCHAR)"RPC_NT_INVALID_TAG";
    case 0xC0020023: return (PUCHAR)"RPC_NT_INVALID_BOUND";
    case 0xC0020024: return (PUCHAR)"RPC_NT_NO_ENTRY_NAME";
    case 0xC0020025: return (PUCHAR)"RPC_NT_INVALID_NAME_SYNTAX";
    case 0xC0020026: return (PUCHAR)"RPC_NT_UNSUPPORTED_NAME_SYNTAX";
    case 0xC0020028: return (PUCHAR)"RPC_NT_UUID_NO_ADDRESS";
    case 0xC0020029: return (PUCHAR)"RPC_NT_DUPLICATE_ENDPOINT";
    case 0xC002002A: return (PUCHAR)"RPC_NT_UNKNOWN_AUTHN_TYPE";
    case 0xC002002B: return (PUCHAR)"RPC_NT_MAX_CALLS_TOO_SMALL";
    case 0xC002002C: return (PUCHAR)"RPC_NT_STRING_TOO_LONG";
    case 0xC002002D: return (PUCHAR)"RPC_NT_PROTSEQ_NOT_FOUND";
    case 0xC002002E: return (PUCHAR)"RPC_NT_PROCNUM_OUT_OF_RANGE";
    case 0xC002002F: return (PUCHAR)"RPC_NT_BINDING_HAS_NO_AUTH";
    case 0xC0020030: return (PUCHAR)"RPC_NT_UNKNOWN_AUTHN_SERVICE";
    case 0xC0020031: return (PUCHAR)"RPC_NT_UNKNOWN_AUTHN_LEVEL";
    case 0xC0020032: return (PUCHAR)"RPC_NT_INVALID_AUTH_IDENTITY";
    case 0xC0020033: return (PUCHAR)"RPC_NT_UNKNOWN_AUTHZ_SERVICE";
    case 0xC0020034: return (PUCHAR)"EPT_NT_INVALID_ENTRY";
    case 0xC0020035: return (PUCHAR)"EPT_NT_CANT_PERFORM_OP";
    case 0xC0020036: return (PUCHAR)"EPT_NT_NOT_REGISTERED";
    case 0xC0020037: return (PUCHAR)"RPC_NT_NOTHING_TO_EXPORT";
    case 0xC0020038: return (PUCHAR)"RPC_NT_INCOMPLETE_NAME";
    case 0xC0020039: return (PUCHAR)"RPC_NT_INVALID_VERS_OPTION";
    case 0xC002003A: return (PUCHAR)"RPC_NT_NO_MORE_MEMBERS";
    case 0xC002003B: return (PUCHAR)"RPC_NT_NOT_ALL_OBJS_UNEXPORTED";
    case 0xC002003C: return (PUCHAR)"RPC_NT_INTERFACE_NOT_FOUND";
    case 0xC002003D: return (PUCHAR)"RPC_NT_ENTRY_ALREADY_EXISTS";
    case 0xC002003E: return (PUCHAR)"RPC_NT_ENTRY_NOT_FOUND";
    case 0xC002003F: return (PUCHAR)"RPC_NT_NAME_SERVICE_UNAVAILABLE";
    case 0xC0020040: return (PUCHAR)"RPC_NT_INVALID_NAF_ID";
    case 0xC0020041: return (PUCHAR)"RPC_NT_CANNOT_SUPPORT";
    case 0xC0020042: return (PUCHAR)"RPC_NT_NO_CONTEXT_AVAILABLE";
    case 0xC0020043: return (PUCHAR)"RPC_NT_INTERNAL_ERROR";
    case 0xC0020044: return (PUCHAR)"RPC_NT_ZERO_DIVIDE";
    case 0xC0020045: return (PUCHAR)"RPC_NT_ADDRESS_ERROR";
    case 0xC0020046: return (PUCHAR)"RPC_NT_FP_DIV_ZERO";
    case 0xC0020047: return (PUCHAR)"RPC_NT_FP_UNDERFLOW";
    case 0xC0020048: return (PUCHAR)"RPC_NT_FP_OVERFLOW";
    case 0xC0030001: return (PUCHAR)"RPC_NT_NO_MORE_ENTRIES";
    case 0xC0030002: return (PUCHAR)"RPC_NT_SS_CHAR_TRANS_OPEN_FAIL";
    case 0xC0030003: return (PUCHAR)"RPC_NT_SS_CHAR_TRANS_SHORT_FILE";
    case 0xC0030004: return (PUCHAR)"RPC_NT_SS_IN_NULL_CONTEXT";
    case 0xC0030005: return (PUCHAR)"RPC_NT_SS_CONTEXT_MISMATCH";
    case 0xC0030006: return (PUCHAR)"RPC_NT_SS_CONTEXT_DAMAGED";
    case 0xC0030007: return (PUCHAR)"RPC_NT_SS_HANDLES_MISMATCH";
    case 0xC0030008: return (PUCHAR)"RPC_NT_SS_CANNOT_GET_CALL_HANDLE";
    case 0xC0030009: return (PUCHAR)"RPC_NT_NULL_REF_POINTER";
    case 0xC003000A: return (PUCHAR)"RPC_NT_ENUM_VALUE_OUT_OF_RANGE";
    case 0xC003000B: return (PUCHAR)"RPC_NT_BYTE_COUNT_TOO_SMALL";
    case 0xC003000C: return (PUCHAR)"RPC_NT_BAD_STUB_DATA";
    case 0xC0020049: return (PUCHAR)"RPC_NT_CALL_IN_PROGRESS";
    case 0xC002004A: return (PUCHAR)"RPC_NT_NO_MORE_BINDINGS";
    case 0xC002004B: return (PUCHAR)"RPC_NT_GROUP_MEMBER_NOT_FOUND";
    case 0xC002004C: return (PUCHAR)"EPT_NT_CANT_CREATE";
    case 0xC002004D: return (PUCHAR)"RPC_NT_INVALID_OBJECT";
    case 0xC002004F: return (PUCHAR)"RPC_NT_NO_INTERFACES";
    case 0xC0020050: return (PUCHAR)"RPC_NT_CALL_CANCELLED";
    case 0xC0020051: return (PUCHAR)"RPC_NT_BINDING_INCOMPLETE";
    case 0xC0020052: return (PUCHAR)"RPC_NT_COMM_FAILURE";
    case 0xC0020053: return (PUCHAR)"RPC_NT_UNSUPPORTED_AUTHN_LEVEL";
    case 0xC0020054: return (PUCHAR)"RPC_NT_NO_PRINC_NAME";
    case 0xC0020055: return (PUCHAR)"RPC_NT_NOT_RPC_ERROR";
    case 0x40020056: return (PUCHAR)"RPC_NT_UUID_LOCAL_ONLY";
    case 0xC0020057: return (PUCHAR)"RPC_NT_SEC_PKG_ERROR";
    case 0xC0020058: return (PUCHAR)"RPC_NT_NOT_CANCELLED";
    case 0xC0030059: return (PUCHAR)"RPC_NT_INVALID_ES_ACTION";
    case 0xC003005A: return (PUCHAR)"RPC_NT_WRONG_ES_VERSION";
    case 0xC003005B: return (PUCHAR)"RPC_NT_WRONG_STUB_VERSION";
    case 0xC003005C: return (PUCHAR)"RPC_NT_INVALID_PIPE_OBJECT";
    case 0xC003005D: return (PUCHAR)"RPC_NT_INVALID_PIPE_OPERATION";
    case 0xC003005E: return (PUCHAR)"RPC_NT_WRONG_PIPE_VERSION";
    case 0xC003005F: return (PUCHAR)"RPC_NT_PIPE_CLOSED";
    case 0xC0030060: return (PUCHAR)"RPC_NT_PIPE_DISCIPLINE_ERROR";
    case 0xC0030061: return (PUCHAR)"RPC_NT_PIPE_EMPTY";
    case 0xC0020062: return (PUCHAR)"RPC_NT_INVALID_ASYNC_HANDLE";
    case 0xC0020063: return (PUCHAR)"RPC_NT_INVALID_ASYNC_CALL";
    case 0x400200AF: return (PUCHAR)"RPC_NT_SEND_INCOMPLETE";
    case 0xC0140001: return (PUCHAR)"STATUS_ACPI_INVALID_OPCODE";
    case 0xC0140002: return (PUCHAR)"STATUS_ACPI_STACK_OVERFLOW";
    case 0xC0140003: return (PUCHAR)"STATUS_ACPI_ASSERT_FAILED";
    case 0xC0140004: return (PUCHAR)"STATUS_ACPI_INVALID_INDEX";
    case 0xC0140005: return (PUCHAR)"STATUS_ACPI_INVALID_ARGUMENT";
    case 0xC0140006: return (PUCHAR)"STATUS_ACPI_FATAL";
    case 0xC0140007: return (PUCHAR)"STATUS_ACPI_INVALID_SUPERNAME";
    case 0xC0140008: return (PUCHAR)"STATUS_ACPI_INVALID_ARGTYPE";
    case 0xC0140009: return (PUCHAR)"STATUS_ACPI_INVALID_OBJTYPE";
    case 0xC014000A: return (PUCHAR)"STATUS_ACPI_INVALID_TARGETTYPE";
    case 0xC014000B: return (PUCHAR)"STATUS_ACPI_INCORRECT_ARGUMENT_COUNT";
    case 0xC014000C: return (PUCHAR)"STATUS_ACPI_ADDRESS_NOT_MAPPED";
    case 0xC014000D: return (PUCHAR)"STATUS_ACPI_INVALID_EVENTTYPE";
    case 0xC014000E: return (PUCHAR)"STATUS_ACPI_HANDLER_COLLISION";
    case 0xC014000F: return (PUCHAR)"STATUS_ACPI_INVALID_DATA";
    case 0xC0140010: return (PUCHAR)"STATUS_ACPI_INVALID_REGION";
    case 0xC0140011: return (PUCHAR)"STATUS_ACPI_INVALID_ACCESS_SIZE";
    case 0xC0140012: return (PUCHAR)"STATUS_ACPI_ACQUIRE_GLOBAL_LOCK";
    case 0xC0140013: return (PUCHAR)"STATUS_ACPI_ALREADY_INITIALIZED";
    case 0xC0140014: return (PUCHAR)"STATUS_ACPI_NOT_INITIALIZED";
    case 0xC0140015: return (PUCHAR)"STATUS_ACPI_INVALID_MUTEX_LEVEL";
    case 0xC0140016: return (PUCHAR)"STATUS_ACPI_MUTEX_NOT_OWNED";
    case 0xC0140017: return (PUCHAR)"STATUS_ACPI_MUTEX_NOT_OWNER";
    case 0xC0140018: return (PUCHAR)"STATUS_ACPI_RS_ACCESS";
    case 0xC0140019: return (PUCHAR)"STATUS_ACPI_INVALID_TABLE";
    case 0xC0140020: return (PUCHAR)"STATUS_ACPI_REG_HANDLER_FAILED";
    case 0xC0140021: return (PUCHAR)"STATUS_ACPI_POWER_REQUEST_FAILED";
    case 0xC00A0001: return (PUCHAR)"STATUS_CTX_WINSTATION_NAME_INVALID";
    case 0xC00A0002: return (PUCHAR)"STATUS_CTX_INVALID_PD";
    case 0xC00A0003: return (PUCHAR)"STATUS_CTX_PD_NOT_FOUND";
    case 0x400A0004: return (PUCHAR)"STATUS_CTX_CDM_CONNECT";
    case 0x400A0005: return (PUCHAR)"STATUS_CTX_CDM_DISCONNECT";
    case 0xC00A0006: return (PUCHAR)"STATUS_CTX_CLOSE_PENDING";
    case 0xC00A0007: return (PUCHAR)"STATUS_CTX_NO_OUTBUF";
    case 0xC00A0008: return (PUCHAR)"STATUS_CTX_MODEM_INF_NOT_FOUND";
    case 0xC00A0009: return (PUCHAR)"STATUS_CTX_INVALID_MODEMNAME";
    case 0xC00A000A: return (PUCHAR)"STATUS_CTX_RESPONSE_ERROR";
    case 0xC00A000B: return (PUCHAR)"STATUS_CTX_MODEM_RESPONSE_TIMEOUT";
    case 0xC00A000C: return (PUCHAR)"STATUS_CTX_MODEM_RESPONSE_NO_CARRIER";
    case 0xC00A000D: return (PUCHAR)"STATUS_CTX_MODEM_RESPONSE_NO_DIALTONE";
    case 0xC00A000E: return (PUCHAR)"STATUS_CTX_MODEM_RESPONSE_BUSY";
    case 0xC00A000F: return (PUCHAR)"STATUS_CTX_MODEM_RESPONSE_VOICE";
    case 0xC00A0010: return (PUCHAR)"STATUS_CTX_TD_ERROR";
    case 0xC00A0012: return (PUCHAR)"STATUS_CTX_LICENSE_CLIENT_INVALID";
    case 0xC00A0013: return (PUCHAR)"STATUS_CTX_LICENSE_NOT_AVAILABLE";
    case 0xC00A0014: return (PUCHAR)"STATUS_CTX_LICENSE_EXPIRED";
    case 0xC00A0015: return (PUCHAR)"STATUS_CTX_WINSTATION_NOT_FOUND";
    case 0xC00A0016: return (PUCHAR)"STATUS_CTX_WINSTATION_NAME_COLLISION";
    case 0xC00A0017: return (PUCHAR)"STATUS_CTX_WINSTATION_BUSY";
    case 0xC00A0018: return (PUCHAR)"STATUS_CTX_BAD_VIDEO_MODE";
    case 0xC00A0022: return (PUCHAR)"STATUS_CTX_GRAPHICS_INVALID";
    case 0xC00A0024: return (PUCHAR)"STATUS_CTX_NOT_CONSOLE";
    case 0xC00A0026: return (PUCHAR)"STATUS_CTX_CLIENT_QUERY_TIMEOUT";
    case 0xC00A0027: return (PUCHAR)"STATUS_CTX_CONSOLE_DISCONNECT";
    case 0xC00A0028: return (PUCHAR)"STATUS_CTX_CONSOLE_CONNECT";
    case 0xC00A002A: return (PUCHAR)"STATUS_CTX_SHADOW_DENIED";
    case 0xC00A002B: return (PUCHAR)"STATUS_CTX_WINSTATION_ACCESS_DENIED";
    case 0xC00A002E: return (PUCHAR)"STATUS_CTX_INVALID_WD";
    case 0xC00A002F: return (PUCHAR)"STATUS_CTX_WD_NOT_FOUND";
    case 0xC00A0030: return (PUCHAR)"STATUS_CTX_SHADOW_INVALID";
    case 0xC00A0031: return (PUCHAR)"STATUS_CTX_SHADOW_DISABLED";
    case 0xC00A0032: return (PUCHAR)"STATUS_RDP_PROTOCOL_ERROR";
    case 0xC00A0033: return (PUCHAR)"STATUS_CTX_CLIENT_LICENSE_NOT_SET";
    case 0xC00A0034: return (PUCHAR)"STATUS_CTX_CLIENT_LICENSE_IN_USE";
    case 0xC0040035: return (PUCHAR)"STATUS_PNP_BAD_MPS_TABLE";
    case 0xC0040036: return (PUCHAR)"STATUS_PNP_TRANSLATION_FAILED";
    case 0xC0040037: return (PUCHAR)"STATUS_PNP_IRQ_TRANSLATION_FAILED";
    default:         return (PUCHAR)"STATUS_UNKNOWN";
    }
}

NTSTATUS
VfsReadDisk(  PVFS_FILESYS  VfsSys,
              ULONGLONG     Offset,
              ULONG         Length,
              PVOID         Buffer )
{
    LARGE_INTEGER   Address;
    NTSTATUS        Status;
    ULONG           AlignedLength;
    IO_STATUS_BLOCK IoStatus;
    PVOID           NonPagedBuffer = NULL;

    //Maindebug("start read");
    ASSERT(Buffer != NULL);
    //printf(" read sector %x \n",(Offset/512));
    if (VfsSys->bFile)
    {
        //Maindebug("\n read from disk 1");
        Address.QuadPart = Offset;
        Status = NtReadFile(  VfsSys->MediaHandle,
                              0,
                              NULL,
                              NULL,
                              &IoStatus,
                              Buffer,
                              Length,
                              &Address,
                              NULL );
    }
    else
    {
        //Maindebug("\n read from disk 2");
        Address.QuadPart = Offset & (~((ULONGLONG)SECTOR_SIZE - 1));
        AlignedLength    = (Length + SECTOR_SIZE - 1)&(~(SECTOR_SIZE - 1));
        AlignedLength   += ((ULONG)(Offset - Address.QuadPart) + SECTOR_SIZE - 1) & (~(SECTOR_SIZE - 1));
        //printf("\n AlignedLength 0x%x",AlignedLength);
        NonPagedBuffer   = malloc(AlignedLength);
        //printf("\n alloc_buf at 0x%x",NonPagedBuffer);
        if (!NonPagedBuffer)
        {
            Status = STATUS_INSUFFICIENT_RESOURCES;
            goto errorout;
        }
        Status = NtReadFile( VfsSys->MediaHandle,
                             0,
                             NULL,
                             NULL,
                             &IoStatus,
                             NonPagedBuffer,
                             AlignedLength,
                             &Address,
                             NULL );
        if (!NT_SUCCESS(Status))
        {
            goto errorout;
        }
        //printf("\n copy to 0x%x with len 0x%x",Buffer,Length);
        RtlCopyMemory( Buffer,(PUCHAR)NonPagedBuffer + (ULONG)(Offset - Address.QuadPart),Length );
        //DEBUG_DumpData(Buffer,20);
    }

errorout:
    if (NonPagedBuffer)
        free(NonPagedBuffer);
    return Status;
}

NTSTATUS
VfsWriteDisk( PVFS_FILESYS    VfsSys,
               ULONGLONG      Offset,
               ULONG          Length,
               PVOID          Buffer )
{
    LARGE_INTEGER   Address;
    NTSTATUS        Status;
    ULONG           AlignedLength;

    IO_STATUS_BLOCK IoStatus;

    PVOID           NonPagedBuffer = NULL;

    ASSERT(Buffer != NULL);

    if (VfsSys->bFile)
    {
        Address.QuadPart = Offset;

        Status = NtWriteFile( VfsSys->MediaHandle,
                              0,
                              NULL,
                              NULL,
                              &IoStatus,
                              Buffer,
                              Length,
                              &Address,
                              NULL );
    }
    else
    {
        Address.QuadPart = Offset & (~((ULONGLONG)SECTOR_SIZE - 1));

        AlignedLength  = (Length + SECTOR_SIZE - 1)&(~(SECTOR_SIZE - 1));

        AlignedLength += ((ULONG)(Offset - Address.QuadPart) + SECTOR_SIZE - 1)
                         & (~(SECTOR_SIZE - 1));

        NonPagedBuffer = malloc(AlignedLength);
        if (!NonPagedBuffer)
        {
            Status = STATUS_INSUFFICIENT_RESOURCES;
            goto errorout;
        }

        if ((AlignedLength != Length) || (Address.QuadPart != (LONGLONG)Offset))
        {
            Status = NtReadFile( VfsSys->MediaHandle,
                                 0,
                                 NULL,
                                 NULL,
                                 &IoStatus,
                                 NonPagedBuffer,
                                 AlignedLength,
                                 &Address,
                                 NULL );

            if(!NT_SUCCESS(Status)){
                goto errorout;
              }
        }

        RtlCopyMemory( (PUCHAR)NonPagedBuffer + (ULONG)(Offset - Address.QuadPart),
                       Buffer, Length );

        Status = NtWriteFile( VfsSys->MediaHandle,
                              0,
                              NULL,
                              NULL,
                              &IoStatus,
                              NonPagedBuffer,
                              AlignedLength,
                              &Address,
                              NULL );
    }

errorout:

    if (NonPagedBuffer)
        free(NonPagedBuffer);

    return Status;
}

NTSTATUS
VfsGetMediaInfo( PVFS_FILESYS VfsSys )
{
    NTSTATUS Status;
    IO_STATUS_BLOCK IoSb;

    Status = NtDeviceIoControlFile( VfsSys->MediaHandle,
                                NULL, NULL, NULL, &IoSb,
                                IOCTL_DISK_GET_DRIVE_GEOMETRY,
                                &(VfsSys->DiskGeometry), sizeof(DISK_GEOMETRY),
                                &(VfsSys->DiskGeometry), sizeof(DISK_GEOMETRY));


    if (!NT_SUCCESS(Status))
    {
        goto errorout;
    }

    Status = NtDeviceIoControlFile( VfsSys->MediaHandle,
                                NULL, NULL, NULL, &IoSb,
                                IOCTL_DISK_GET_PARTITION_INFO,
                                &(VfsSys->PartInfo), sizeof(PARTITION_INFORMATION),
                                &(VfsSys->PartInfo), sizeof(PARTITION_INFORMATION));

    if (!NT_SUCCESS(Status))
    {
        goto errorout;
    }

errorout:

    return Status;
}

NTSTATUS
VfsLockVolume( PVFS_FILESYS VfsSys )
{
    NTSTATUS Status;
    IO_STATUS_BLOCK IoSb;

    Status = ZwFsControlFile( VfsSys->MediaHandle,
                              NULL, NULL, NULL, &IoSb,
                              FSCTL_LOCK_VOLUME,
                              NULL, 0, NULL, 0 );

    if (!NT_SUCCESS(Status))
    {
        printf("disk: Error when locking volume: Status = %xh %s...\n",
               (int) Status, VfsStatusToString(Status));

        goto errorout;
    }

errorout:

    return Status;
}


NTSTATUS
VfsUnLockVolume( PVFS_FILESYS VfsSys )
{
    NTSTATUS Status;
    IO_STATUS_BLOCK IoSb;

    Status = ZwFsControlFile( VfsSys->MediaHandle,
                              NULL, NULL, NULL, &IoSb,
                              FSCTL_UNLOCK_VOLUME,
                              NULL, 0, NULL, 0 );

    if (!NT_SUCCESS(Status))
    {
        printf("disk: Error when unlocking volume ...\n");
        goto errorout;
    }

errorout:

    return Status;
}

NTSTATUS
VfsDisMountVolume( PVFS_FILESYS VfsSys )
{
    NTSTATUS Status;
    IO_STATUS_BLOCK IoSb;

    Status = ZwFsControlFile( VfsSys->MediaHandle,
                              NULL, NULL, NULL, &IoSb,
                              FSCTL_DISMOUNT_VOLUME,
                              NULL, 0, NULL, 0 );

    if (!NT_SUCCESS(Status))
    {
        printf("disk: Error when dismounting volume ...\n");
        goto errorout;
    }

errorout:

    return Status;
}

NTSTATUS
VfsOpenDevice(  PVFS_FILESYS VfsSys,
                 PUCHAR        DeviceName )
{
    NTSTATUS Status;
    UNICODE_STRING UnicodeFilespec;
    OBJECT_ATTRIBUTES ObjectAttributes;
    HANDLE FileHandle;
    IO_STATUS_BLOCK Iosb;
    USHORT NameLength = 0;

    ANSI_STRING AnsiFilespec;
    SHORT  UnicodeName[256];
    UCHAR  AnsiName[256];
    /*
	DefineDosDeviceW(
		0,
		0,
		0);*/

    memset(UnicodeName, 0, sizeof(SHORT) * 256);
    memset(UnicodeName, 0, sizeof(UCHAR) * 256);

    NameLength = strlen((char *)DeviceName);

    ASSERT(NameLength < 256);

    if (DeviceName[0] == '\\')
    {
        RtlCopyMemory(AnsiName, DeviceName, NameLength);
    }
    else
    {
        RtlCopyMemory(&AnsiName[0], "\\DosDevices\\", 12);
        RtlCopyMemory(&AnsiName[12], DeviceName, NameLength);
        NameLength += 12;
    }

    AnsiFilespec.MaximumLength =
    AnsiFilespec.Length = NameLength;
    AnsiFilespec.Buffer = (char *)AnsiName;


    UnicodeFilespec.MaximumLength = 256 * 2;
    UnicodeFilespec.Length = 0;
    UnicodeFilespec.Buffer = (PWSTR)UnicodeName;

    RtlAnsiStringToUnicodeString(&UnicodeFilespec, &AnsiFilespec, FALSE);
    InitializeObjectAttributes(&ObjectAttributes,
                               &UnicodeFilespec,
                               OBJ_CASE_INSENSITIVE,
                               NULL,
                               NULL );
    Status = ZwCreateFile(&FileHandle,
                          (GENERIC_READ | GENERIC_WRITE | SYNCHRONIZE),
                          &ObjectAttributes,
                          &Iosb,
                          0,
                          FILE_ATTRIBUTE_NORMAL,
                          FILE_SHARE_WRITE | FILE_SHARE_READ,
                          FILE_OPEN,
                          FILE_SYNCHRONOUS_IO_NONALERT,
                          NULL,
                          0);

    //
    // Check the system service status
    //
    if( !NT_SUCCESS(Status) )
    {
        printf("disk: Create system service failed status = 0x%0x\n",(int) Status);

        return Status;
    }
    //
    // Check the returned status too...
    //
    if(!NT_SUCCESS(Iosb.Status) )
    {
        printf("disk: Create failed with status = 0x%0x\n",(int)Iosb.Status);
        return Status;
    }

    VfsSys->MediaHandle = FileHandle;

    return Status;
}

NTSTATUS
VfsCloseDevice( PVFS_FILESYS VfsSys)
{
    NTSTATUS Status = STATUS_SUCCESS;

    if(VfsSys->MediaHandle)
    {
        Status = NtClose(VfsSys->MediaHandle);
    }

    return Status;
}

NTSTATUS
VfsDevtoLetter(char *DevName, const char *driver)
{
     NTSTATUS Status = STATUS_SUCCESS;
     printf("\n mount %s to %s",DevName,driver);

	if(!DefineDosDeviceA(DDD_RAW_TARGET_PATH,(LPCSTR)driver,(LPCSTR)DevName)){
               printf(" ERROR ");
	       return -1;
  	  }
	return Status;
}

int Unmount(const char *driver)
{

	char	DosDevName[256];
	HANDLE	device;
	ULONG	dwBytes;

	sprintf(DosDevName, "\\\\.\\%s", driver);
	printf("\n umount: DosDevName: %s\n", DosDevName);

	device = CreateFileA(
		DosDevName,
		GENERIC_READ | GENERIC_WRITE,
		FILE_SHARE_READ | FILE_SHARE_WRITE,
		NULL,
		OPEN_EXISTING,
		FILE_ATTRIBUTE_NORMAL,
		NULL );

	if (device == INVALID_HANDLE_VALUE)
	{
		printf("Unmount: open %s error.\n", DosDevName);
		return -1;
	}

	if (!DeviceIoControl(
		device,
		FSCTL_LOCK_VOLUME,
		NULL,
		0,
		NULL,
		0,
		&dwBytes,
		NULL ))
	{
		printf("Unmount: ioctl: LockVolume %s error.\n", DosDevName);

	}

	if (!DeviceIoControl(
		device,
		FSCTL_DISMOUNT_VOLUME,
		NULL,
		0,
		NULL,
		0,
		&dwBytes,
		NULL))
	{
		printf("Unmount: ioctl: DisMount %s error.\n", DosDevName);
	}

	CloseHandle(device);

	if (!DefineDosDeviceA(
		DDD_REMOVE_DEFINITION,
		(LPCSTR)driver,
		NULL ))
	{
		printf("Unmount: Remove %s error.\n", driver);
		return -1;
	}

	return 0;
}

#else

NTSTATUS VfsReadDisk(PVFS_FILESYS  VfsSys,
                unsigned long long int Offset,
                unsigned long int Length,
                void *Buffer )
{
    unsigned long long Address;
    int Status = -1;
    unsigned long AlignedLength;
    void *NonPagedBuffer = NULL;

    assert(Buffer != NULL);
    if (VfsSys->bFile) {
        Address = Offset;
        // seek to Address & read length to Buffer
        Status = lseek(VfsSys->MediaHandle, Address, SEEK_SET);
        if (Status == -1) {
            printf("Error during seek to Address %llu %s\n", Address, strerror(errno));
            return Status;
        }
        
        Status = read(VfsSys->MediaHandle, Buffer, Length);
        if (Status == -1) {
            printf("Error during read: %s\n", strerror(errno));
            return Status;
        }

    } else {
        Address = Offset & (~((unsigned long long int)SECTOR_SIZE - 1));
        AlignedLength    = (Length + SECTOR_SIZE - 1)&(~(SECTOR_SIZE - 1));
        AlignedLength   += ((unsigned long)(Offset - Address) + SECTOR_SIZE - 1) & (~(SECTOR_SIZE - 1));
        NonPagedBuffer   = malloc(AlignedLength);
        if (!NonPagedBuffer) {
            Status = errno;
            if (NonPagedBuffer)
                free(NonPagedBuffer);
            return Status;
        }
        if ((AlignedLength != Length) || (Address != Offset)) {
            // seek to Address & read Alignedlength to NonPagedBuffer
            Status = lseek(VfsSys->MediaHandle, Address, SEEK_SET);
            if (Status == -1) {
                printf("Error during aligned seek: %s\n", strerror(errno));
                if (NonPagedBuffer)
                    free(NonPagedBuffer);
                return Status;
            }
            
            Status = read(VfsSys->MediaHandle, NonPagedBuffer, AlignedLength);
            if (Status == -1) {
                printf("Error during aligned read: %s\n", strerror(errno));
                if (NonPagedBuffer)
                    free(NonPagedBuffer);
                return Status;
            }
        }
        memcpy ( (unsigned char *)NonPagedBuffer + (unsigned long)(Offset - Address),
                       Buffer, Length );
    }

    if (NonPagedBuffer)
        free(NonPagedBuffer);

    return Status;
}


NTSTATUS VfsWriteDisk(PVFS_FILESYS VfsSys,
                 unsigned long long Offset,
                 unsigned long Length,
                 void * Buffer)
{
    unsigned long long Address;
    int Status;
    unsigned long AlignedLength;
    void *NonPagedBuffer = NULL;

    assert(Buffer != NULL);

    if (VfsSys->bFile) {
        Address = Offset;

        // seek to Address & write file from buffer with length
        Status = lseek(VfsSys->MediaHandle, Address, SEEK_SET);
        if (Status == -1) {
            printf("Error during seek to Address %llu %s\n", Address, strerror(errno));
            return Status;
        }
        Status = write(VfsSys->MediaHandle, Buffer, Length);
        if (Status == -1) {
            printf("Error during write: %s\n", strerror(errno));
            return Status;
        }
    } else {
        Address = Offset & (~((ULONGLONG)SECTOR_SIZE - 1));
        
        AlignedLength  = (Length + SECTOR_SIZE - 1)&(~(SECTOR_SIZE - 1));

        AlignedLength += ((ULONG)(Offset - Address) + SECTOR_SIZE - 1)
                         & (~(SECTOR_SIZE - 1));

        NonPagedBuffer = malloc(AlignedLength);
        if (!NonPagedBuffer) {
            Status = errno;
            if (NonPagedBuffer)
                free(NonPagedBuffer);
            return Status;
        }

        if ((AlignedLength != Length) || (Address != Offset)) {

            // seek to Address & read file from NonPagedBuffer with AlignedLength
            Status = lseek(VfsSys->MediaHandle, Address, SEEK_SET);
            if (Status == -1) {
                printf("Error during aligned seek: %s\n", strerror(errno));
                if (NonPagedBuffer)
                    free(NonPagedBuffer);
                return Status;
            }
            
            Status = read(VfsSys->MediaHandle, NonPagedBuffer, AlignedLength);
            if (Status == -1) {
                printf("Error during aligned read: %s\n", strerror(errno));
                if (NonPagedBuffer)
                    free(NonPagedBuffer);
                return Status;
            }

        }

        memcpy ( (unsigned char *)NonPagedBuffer + (unsigned long)(Offset - Address),
                       Buffer, Length );

        // seek to Address & write file from NonPagedBuffer with AlignedLength
        Status = lseek(VfsSys->MediaHandle, Address, SEEK_SET);
        if (Status == -1) {
            printf("Error during aligned seek 2: %s\n", strerror(errno));
            if (NonPagedBuffer)
                free(NonPagedBuffer);
            return Status;
        }
        Status = write(VfsSys->MediaHandle, NonPagedBuffer, AlignedLength);
        if (Status == -1) {
            printf("Error during aligned write: %s\n", strerror(errno));
            if (NonPagedBuffer)
                free(NonPagedBuffer);
            return Status;
        }
    }

    return Status;
}

NTSTATUS VfsGetMediaInfo( PVFS_FILESYS VfsSys )
{
    // Not yet implemented for Linux
    // Note: needs to be corrected to STATUS_SUCCESS when higher-level logic is fixed
    return 1;
}

NTSTATUS VfsLockVolume( PVFS_FILESYS VfsSys )
{
    // Not yet implemented for Linux
    return STATUS_SUCCESS;
}

NTSTATUS VfsUnLockVolume( PVFS_FILESYS VfsSys )
{
    // Not yet implemented for Linux
    return STATUS_SUCCESS;
}

NTSTATUS
VfsDevtoLetter(char *DevName, const char *driver)
{
    // No direct meaning on Linux, we may want to check here if device is mounted..
    return STATUS_SUCCESS;
}

NTSTATUS VfsOpenDevice(PVFS_FILESYS VfsSys,
                  PUCHAR DeviceName)
{
    VfsSys->MediaHandle = open ((char*)DeviceName, O_RDONLY | O_LARGEFILE);
    if (VfsSys->MediaHandle == -1) {
        printf("Error during open <%s>: %s\n", DeviceName, strerror(errno));
    }
    
    return VfsSys->MediaHandle;
}

NTSTATUS VfsCloseDevice(PVFS_FILESYS VfsSys)
{
    int Status = -1;

    if(VfsSys->MediaHandle != -1) {
        Status = close(VfsSys->MediaHandle);
    }

    return Status;
}

int Unmount(const char *driver)
{
    // currently dummy - later we may need to unmount a device here
    printf("Unmount %s\n", driver);
    return 0;
}

#endif
