######################################################################
# Automatically generated by qmake (2.01a) Mi. Aug 18 20:50:12 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myform.h types.h vfs.h
SOURCES += Disk.c \
           main.cpp \
           MyForm.cpp \
           vfs.c
